### ISSUE TITLE
Enhancement: Nesting Subfolders

### ISSUE THREAD

**Issue by Dumbhuman** [earlSt1/vtt-compendium-folders#1]
I've been waiting for someone to develop a folder management structure for compendiums (and macros too, but that's a whole other mess), so thank you very much for your hard work!  I'm sure this suggestion is one you've already thought about, but I didn't see it explicitly listed for the future so I figured I'd speak up just in case.

Creating custom folders and subfolders is something that would massively increase the usefulness of the compendium for me.  Currently I have a character-building system using the item subfolders, but really I'd like it to exist in compendium form so it can be more efficient in terms of how it loads into the game (and transfers from world to world).  The number of nesting of subfolders allowed for items works about well enough for me, but having even one more level of nesting would be even better if possible.

![image](https://user-images.githubusercontent.com/63615591/88475737-8e656b80-cee7-11ea-836d-76da65754372.png)

**Comment by earlSt1** [comment]
This is something I'll likely add once i've got the basic folder functionality sorted. My aim is to replicate the folder systems that the other tabs use as much as I can. Thanks for mentioning though, I've added it to the Future section in the readme.

**Comment by earlSt1** [comment]
Nesting branch created, in a somewhat stable state. 

If you want to try out the nesting folders, you can use [this manifest](https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/nesting/module.json)

**Comment by earlSt1** [comment]
Now included in v1.0.0
