### ISSUE TITLE
Recent update broke Merging by Name

### ISSUE THREAD

**Issue by sneat** [earlSt1/vtt-compendium-folders#100]
**Describe the bug**
The recent [update](https://github.com/earlSt1/vtt-compendium-folders/pull/96) missed a couple of references to `.data` that doesn't exist on the `existingFolder` value. Correct reference should be `existingFolder.flags.cf...`

Locations are:
https://github.com/earlSt1/vtt-compendium-folders/blob/fic-api/fic-folders.js#L1136-L1137
https://github.com/earlSt1/vtt-compendium-folders/blob/fic-api/fic-folders.js#L1206
Alternatively, search for `existingFolder.data`.

**To Reproduce**
Export Folder Structure to a compendium.
Export the same Folder Structure to a compendium ticking the "Merge by Name" option.

**Information**
- FoundryVTT Version: 0.8.0
- Compendium Folders Version: 2.3.5
- Game System + Version: dnd5e 1.4.2
- All other modules disabled? n

**Comment by earlSt1** [comment]
Ahh thanks for reporting this, I'll jump on this in the evening.

**Comment by earlSt1** [comment]
Fixed in v2.3.51
