### ISSUE TITLE
Fix my Compendium issue

### ISSUE THREAD

**Issue by bitvypr** [earlSt1/vtt-compendium-folders#105]
Please attach a copy of the error message that you get in the popup window

**Information**
- FoundryVTT Version 8.9
- Compendium Folders Version 2.3.52
- Game System + Version DnD5e 1.4.2
- All other modules disabled? (y/n) n
[BadPaths.txt](https://github.com/earlSt1/vtt-compendium-folders/files/7069808/BadPaths.txt)

**Comment by earlSt1** [comment]
Hi, annoyingly I forgot to include the error in the text output. I'll include this fix in the next release. In the meantime can you try using the test version of CF and see if you get any errors above the MESSAGES line, or if you get further than that error dialog?

To install the test version uninstall your current CF and install this one using the manifest input at the bottom of the module install screen: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json

**Comment by bitvypr** [comment]
After answering the question about other mods being installed, I tried it
with only the bare minimum. I got everything downloaded and organized. A
lot of Mr Primates images are missing, but I think that's on him.

Thanks Much!
--Jeff

**Comment by earlSt1** [comment]
Root issue fixed in v2.3.53
