### ISSUE TITLE
Incompatibility with 'Dig Down'

### ISSUE THREAD

**Issue by simulacrum-1** [earlSt1/vtt-compendium-folders#109]
**Describe the bug**
I think the video shows it best. Duplicates folder structure.

**To Reproduce**
Install dig down and 'Export folder structure' to compendium.

https://user-images.githubusercontent.com/68729767/133107902-a0c1c5b5-7902-4e66-b38a-c2ff1e8d9de2.mov

![Screenshot 2021-09-13 at 15 41 57](https://user-images.githubusercontent.com/68729767/133107965-2dbe3045-5e7c-42d7-99bd-07ae25a9dae0.jpg)

**Expected behavior**

**Screenshots**

**Information**
- FoundryVTT Version ![Screenshot 2021-09-13 at 16 03 53](https://user-images.githubusercontent.com/68729767/133108324-c3fb42fc-9b5b-4b67-8a4b-cfb81bba1eb1.jpg)
- Compendium Folders Version
- Game System + Version
- All other modules disabled? (y/n)

**Comment by earlSt1** [comment]
Hi, thanks for the bug report. I had a feeling that the digdown module would cause some issues when it released. Didnt realise it affected the compendium search bar. I'll check it out when i have some time

**Comment by simulacrum-1** [comment]
Hi earlSt1,
I spoke with theripper93 and he said if it's his fault or he needs to add compatibility code you can contact him.

**Comment by earlSt1** [comment]
So I just tested this on my machine with latest Compendium Folders and Dig Down enabled, and I'm not getting the duplicating folders you have in that video. I'm still getting the warning from libwrapper but thats not a problem. Can you try with everything but CF and Dig Down disabled?

**Comment by simulacrum-1** [comment]
Oh that's not a scene copy button that's the name of the compendium. It's WFRP system styling making it look like a button. When I saw the lib wrapper warning I assume it was dig down causing the error. Let me check.

**Comment by simulacrum-1** [comment]
I'll run conflict finder tonight.

**Comment by simulacrum-1** [comment]
I just ran CF & Did Down. Well it didn't create all those duplicate folders but it did fail to put everything in the folder.
I'm on Chrome, on the Forge on a Mac if that's relevant.
I'll try later with conflict finder to find the culprit that's causing the crazy folders.

![Screenshot 2021-09-14 at 14 01 17](https://user-images.githubusercontent.com/68729767/133263084-346b39b9-f055-4aad-879b-abbafb1b5e9e.jpg)
![Screenshot 2021-09-14 at 14 00 14](https://user-images.githubusercontent.com/68729767/133263090-3dadcba1-8a9d-4a30-a9a7-16f4f9af6d0d.jpg)

**Comment by simulacrum-1** [comment]
I deleted the folder 'If Looks Could Kill' which I think had corrupted and must have been causing it to go crazy. After that everything behaved normally. I ran 'find the culprit' with no further issues. I think I can close issue this now. Thanks for looking into it.

**Comment by earlSt1** [comment]
Ahh perhaps your compendium folders got a bit glitched. If it happens again you can try and run the Fix/Validate Compendium tool found in the module settings :smile:
