### ISSUE TITLE
Deleted a Compendium Folder, Cannot Re-Add Compendium Folder

### ISSUE THREAD

**Issue by claycle** [earlSt1/vtt-compendium-folders#110]
After deleting a compendium folder (within a compendium), I can no longer add the same compendium folder to the compendium.

For example, in the Compendium "00 Peru" I created the folder "00 Peru Scenes". I then imported and exported some scenes to that compendium folder. After seeing how Compendium Folders worked, I deleted the folder within the compendium (00 Peru Scenes) and then tried to add it again. At this point, I get the following error:

![image](https://user-images.githubusercontent.com/419840/133165725-741bf724-d58b-44a1-ac7d-5f879d176aa6.png)

![image](https://user-images.githubusercontent.com/419840/133165527-37fc5e88-9931-4e24-90bc-a51e922e127f.png)

![image](https://user-images.githubusercontent.com/419840/133165926-236991de-c0c7-4e77-8344-6c849eb9e720.png)

**Comment by earlSt1** [comment]
Hi, thanks for the bug report, ill check it out when i have some time. From the looks of it the problem might go away after refreshing the page. Can you try that for the time being?

**Comment by claycle** [comment]
Bug exists across multiple computers, OSes, and browsers. Restarting Foundry server has no effect. Refresh has no impact - bug still happens.

**Comment by earlSt1** [comment]
Hmm I can't seem to replicate it. It may be that it got accidentally hidden by Compendium Folders, can you edit a folder and see if the "00 Peru Scenes" compendium appears at the bottom in the list?

**Comment by claycle** [comment]
Zoiks, yes, it was "hidden" down in another folder for macros - not sure how it got _there_, but, there it is. Sorry for the noise.
