### ISSUE TITLE
Getting 'Installation failed: Forbidden' error while trying to install.

### ISSUE THREAD

**Issue by RakeshP94** [earlSt1/vtt-compendium-folders#111]
**Describe the bug**
Unable to install the module from Module Installer with 'Installation failed: Forbidden' error.

**To Reproduce**
Install from Module Installer

**Expected behavior**
Installs module

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/38881694/134109671-f76ed1f7-9e20-4f3a-8d5a-fe5a3510244c.png)

**Information**
- FoundryVTT 0.8.9
- Compendium Folders 2.3.0
- Game System + Version (N/A)
- All other modules disabled?  (N/A)

**Comment by earlSt1** [comment]
Hi, thats strange, are you able to install other modules?

**Comment by RakeshP94** [comment]
Yes, I am able to install others. I even tried downloading the module files from GitHub and putting it into the modules folder (renamed to _compendium-folders_). It's showing up in the modules list and I am able to use it, but it is weirdly showing as version 2.2.44 instead of 2.3.0.

**Comment by earlSt1** [comment]
> I even tried downloading the module files from GitHub and putting it into the modules folder (renamed to _compendium-folders_). It's showing up in the modules list and I am able to use it, but it is weirdly showing as version 2.2.44 instead of 2.3.0.

That's likely because the main branch is 0.7.x, if you use this link and follow the same steps you did it should get 2.3.53: https://github.com/earlSt1/vtt-compendium-folders/releases/download/2.3.53/2.3.53.zip

**Comment by RakeshP94** [comment]
> 
> 
> That is very weird. Are you self hosting or running your world through Forge?

I am using Oracle Free Tier. OS is Ubuntu.

**Comment by RakeshP94** [comment]
> That's likely because the main branch is 0.7.x, if you use this link and follow the same steps you did it should get 2.3.53: https://github.com/earlSt1/vtt-compendium-folders/releases/download/2.3.53/2.3.53.zip

Yep, that worked. Version is 2.3.53 in the module list as well.

**Comment by earlSt1** [comment]
I saw someone on the discord had this issue with a few modules too, it may have been a hiccup on GitHub's end. I'll close this issue for the time being but thanks for raising it :smile:
