### ISSUE TITLE
Feature request: Move folders within a compendium

### ISSUE THREAD

**Issue by jflevesque** [earlSt1/vtt-compendium-folders#115]
Organizing content inside a compendium is really simpler using this module. The only feature I am missing is the option to move a folder to a different folder. Very useful when you are not certain of how you want things organized.

From what I could see, it seems like the feature is available to move/reorder compendiums themselves from the compendium tab in Foundry, but this feature is missing from within the compendium itself.

**Comment by earlSt1** [comment]
Hi, thanks for the feature request. Just as an update I've figured out a way to move folders using the API, soon I'll start working on improving the compendium window so it's like the sidebar (so you can drag/drop).

**Comment by jflevesque** [comment]
Nice, glad to hear it! :D

**Comment by earlSt1** [comment]
Hi, I've finally managed to figure out a way to implement this and the feature needs a bit of testing (as well as some others).

If you'd like to test, you can install the test version using this manifest: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/09x-update/test/module.json
I **strongly recommend** backing up all your data first in case something breaks though

**Comment by earlSt1** [comment]
Implemented in v2.4.4
