### ISSUE TITLE
Compendium Folders stopped working upon adding another folder within compendium.

### ISSUE THREAD

**Issue by KJTailor** [earlSt1/vtt-compendium-folders#117]
So far the module worked great. However, when I added another subfolder to a folder with already existing subfolders, it suddenly stopped working and instead is now displaying ~20 #CFTempentities.

I followed the clean-up instructions from the FAQ, made sure CF is up to date, and tried fixing/validating the compendium via the settings. The CFTempentities are flickering in the process, but when the fixing tool declares the compendium fixed, nothing has changed. Repeating the process with the compendium closed results in the same outcome.

What else could I try to fix it?

**Information**
- FoundryVTT Version 0.8.9
- Compendium Folders Version 2.3.53
- Game System + Version DnD5e 1.5.3
- All other modules disabled? No

![image](https://user-images.githubusercontent.com/87787745/142604064-7f768dd3-3310-4cbf-be8f-d62e7e4937af.png)
![image](https://user-images.githubusercontent.com/87787745/142604163-98720019-da96-4fdc-9909-be98aa4adfaf.png)

**Comment by earlSt1** [comment]
Hi, can you try using this testing version and see if it fixes it? You'll need to uninstall your current version of CF and install this one using this manifest link: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json. It will look like the same module version, but will have updated code

I strongly recommend backing up your compendiums/worlds just in case.

**Comment by KJTailor** [comment]
I switched over to the test version and it worked like a charm. Thank you.
What do we do from here? I assume you'll update the code to a new updated version? Anything I need to do?

**Comment by earlSt1** [comment]
Great to hear. You can keep that test version and when I release the main version you will be able to update to it from the test version.

**Comment by earlSt1** [comment]
Fixed in v2.3.60
