### ISSUE TITLE
"Export Folder Structure" not listed in Playlists tab

### ISSUE THREAD

**Issue by Mist-Hunter** [earlSt1/vtt-compendium-folders#118]
**Describe the bug**

I look forward to using this great looking module. Thank you for your work on it! I don't know if I'm doing something wrong, or perhaps playlist folders aren't supported. Posting here in case it's unintended.

**To Reproduce**

Right click a playlist folder. 

**Expected behavior**

**Screenshots**

Actors
![image](https://user-images.githubusercontent.com/6420684/142770384-a4356a77-52c3-4502-a88b-54149fe2eaa9.png)

Playlists
![image](https://user-images.githubusercontent.com/6420684/142770391-d03e717a-ebd9-40be-959e-db2a33e240fc.png)

**Information**
- FoundryVTT Version **0.8.9**
- Compendium Folders Version **2.3.53**
- Game System + Version **5E 1.5.5**
- All other modules disabled? (y/n)  yes
- 
![image](https://user-images.githubusercontent.com/6420684/142770407-7516d5a8-a6c4-4cd5-afcd-eec2c3eac56a.png)

**Comment by earlSt1** [comment]
Playlist folders are currently unsupported as they arrived in 0.8.x and i was focusing on getting the module to work for 0.8.x :smile:

I'll add it to my todo list! (after getting macro folders + compendium folders working in 0.8.x)

**Comment by Mist-Hunter** [comment]
Thank you :)

**Comment by earlSt1** [comment]
Implemented in v2.4.4
