### ISSUE TITLE
Newest Version: Problem with the TDE/DSA5 Modules - english compendiums

### ISSUE THREAD

**Issue by vt-tom** [earlSt1/vtt-compendium-folders#120]
**Describe the bug**
The last update creates a problem with the modules for the TDE/DSA5 System it shows beside the german compendiums also the english ones. They can't be used or opend, but still show up under compendiums.

**Expected behavior**
Only the compendiums should show up matching the language which was chosen by the first start of the world.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/144707267-99a0f8ff-f2b5-4974-9b8c-7a1084e32fec.png)

**Information**
- FoundryVTT Version: 8.9
- Compendium Folders Version: 2.3.61 (.59 was fine)
- Game System + Version: TDE/DSA5 2.4.1
- All other modules disabled? (y/n): y

**Comment by earlSt1** [comment]
Hi, can you try again with v2.3.62? I think this may be related to another issue which i fixed.

**Comment by vt-tom** [comment]
Nope, not fixed sorry.

**Comment by earlSt1** [comment]
Yep, i was experiencing this too and found what was causing it. Just pushed another quick release, it should fix it now (v2.3.63)

**Comment by vt-tom** [comment]
Fixed. This is what i love so much in the Foundry Community. Everyone is really commited in helpen each other.
Thank you very much.
