### ISSUE TITLE
Folders within compendium not shown, error in console

### ISSUE THREAD

**Issue by manfred7168** [earlSt1/vtt-compendium-folders#121]
**Describe the bug**
Today, when opening a module actors compendium the folder structure is not shown. Instead I found an error in the console:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
[Detected 1 package: compendium-folders]
    at Function.createFolderWithinCompendium (modules/compendium-folders/fic-folders.js:1464)
    at modules/compendium-folders/fic-folders.js:1498
    at Array.forEach (<anonymous>)
    at Function.createFoldersWithinCompendium (modules/compendium-folders/fic-folders.js:1493)
    at modules/compendium-folders/fic-folders.js:713

**Expected behavior**
Folders should be shown

**Information**
- FoundryVTT Version 0.8.9
- Compendium Folders Version 2.3.63
- Game System + Version  PF2e 2.20.2.9271
- All other modules disabled? (y/n)   nearly, only these are left active: compendium-folders, Library: Scene Packer, my new module

**Comment by earlSt1** [comment]
Sorry for the delay in getting back to you. Are you still getting this error (even with the latest version 2.3.64 / 2.4.1)?

**Comment by manfred7168** [comment]
I got around this by rebuilding the compendium. So I cannot reproduce it. Please close the issue.
