### ISSUE TITLE
Context menus for compendia not working

### ISSUE THREAD

**Issue by Tommycore** [earlSt1/vtt-compendium-folders#122]
**Describe the bug**
Contextmenus do not show for compendia in the compendium tab. They do show for folders though.

**To Reproduce**
- Start world in Foundry.
- Activate *Compendium Folders* and *libwrapper* modules.
- Open Compendium tab.
- Rightclick on any compendium in the tab.

**Expected behavior**
Show a context menu for the clicked compendium

**Information**
- FoundryVTT Version 9.235
- Compendium Folders Version 2.4.0
- Game System + Version HeXXen 0.8.0
- All other modules disabled? Active modules are libwrapper 1.11.0.0 and a content module relying on Compendium Folders.

**Comment by earlSt1** [comment]
Can you try again by uninstalling your current version and installing via this manifest? https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/09x-update/test/module.json

**Comment by earlSt1** [comment]
Fixed in v2.4.1
