### ISSUE TITLE
Enhancement: remember last selection for Destination Pack

### ISSUE THREAD

**Issue by dmaneyapanda** [earlSt1/vtt-compendium-folders#127]
**Describe the bug**
Enhancement request: when exporting a specific type of entity (actor, item, scene, etc.) using the Export Folder Structure menu item, remember the Destination Pack previously used and pre-set it to that value.

My use case: 
I have two different Actor compendiums, one from DnDBeyond (imported using another tool), and one for "My Actors" which is where I store various foldered Actors for organizational reasons (see #126 ).  The DDB compendium is unlocked (so an automated process can update it) but should only ever be updated by that automated process; any time I am manually exporting something to a compendium, it should be going to My Actors.  

But every time I Export Folder Structure, the default pack is set to the DDB compendium, and I need to remember to change it to the correct one.  It would be ideal if the game would remember the last selection made and use it as the default destination.  Obviously, this would have to be different for each type of entity, since they have different destination pack options.

I have a similar use case for pretty much every entity type that can be exported.

Thanks for considering!

**Comment by earlSt1** [comment]
Hi, this is a good idea! Shouldn't be difficult to implement so i'll have a look into it at the weekend.

**Comment by earlSt1** [comment]
Implemented in v2.4.2
