### ISSUE TITLE
Using old `CONST.COMPENDIUM_ENTITY_TYPES` instead of `CONST.COMPENDIUM_DOCUMENT_TYPES.filter(t => t !== "Adventure")`;

### ISSUE THREAD

**Issue by arcanistzed** [earlSt1/vtt-compendium-folders#133]
https://github.com/earlSt1/vtt-compendium-folders/blob/db3901752408227dea47a526faa69ea197bb1f67/compendium-folders.js#L869

This means that Adventure appears as an option for compendiums even though core is not ready for users to use them.

**Comment by earlSt1** [comment]
Thanks for spotting this, will make sure to update it for next release :smile:

**Comment by arcanistzed** [comment]
aeb0808feb05ea2263a20ebea2992a287f5b2284
