### ISSUE TITLE
Fix pt-BR missing translations

### ISSUE THREAD

**Issue by MagelaCE** [earlSt1/vtt-compendium-folders#134]
Here the JSON archive with update translations
[pt-BR.zip](https://github.com/earlSt1/vtt-compendium-folders/files/8105219/pt-BR.zip)

**Comment by earlSt1** [comment]
Hi, sorry for the wait.

Thanks for these! I'll update the translations and include you in the contributions section on the readme :smile:

**Comment by earlSt1** [comment]
Implemented in v2.4.4
