### ISSUE TITLE
Rename swedish language to "Svenska"

### ISSUE THREAD

**Issue by wake42** [earlSt1/vtt-compendium-folders#137]
in https://github.com/earlSt1/vtt-compendium-folders/blob/63577ac7129e6dfdd813d85d27cd049aa670413e/module.json#L40 the Swedish language is written in English while all other languages are translated to their own language. It should be called "Svenska".

**Comment by earlSt1** [comment]
Thanks for pointing that out, will be included in next release :smile:

**Comment by earlSt1** [comment]
Implemented in v2.4.4
