### ISSUE TITLE
Bug with folders in Compendium

### ISSUE THREAD

**Issue by Jonwh25** [earlSt1/vtt-compendium-folders#144]
So I have a rather large compendium full of folders.  It was working great until the latest update (v2.4.5) running on Foundry V9.269 and Dnd5e v1.6.1

Now all my folders show
![image](https://user-images.githubusercontent.com/60674327/171295822-0e115f51-6d7c-4eea-b3db-9b43aa4ef6e3.png)

and when I open the folder and look at the console log I see this
![image](https://user-images.githubusercontent.com/60674327/171295850-cff8518c-4616-4d54-b523-dc8f8cf96c93.png)

**Comment by rbl047** [comment]
Same here!

**Comment by earlSt1** [comment]
Hi, can you try running this macro and sending me the output from the console?
```js
console.log(game.settings.get('compendium-folders','cached-folder'))
```

You can copy the output by right clicking on the result and selecting Copy Object like this:
![image](https://user-images.githubusercontent.com/13738280/171363167-d81a5785-8973-43cc-abf0-c91223720915.png)

**Comment by Jonwh25** [comment]
Here you go

![image](https://user-images.githubusercontent.com/60674327/172703476-f76acdf0-9242-4d6c-96ef-0d7b239405e3.png)


From Copy Object

**Comment by earlSt1** [comment]
Thanks, have retrieved the object and will look into it tomorrow

**Comment by Jonwh25** [comment]
Thanks.  I rolled back to 2.4.3 and the folders work again. I'll stay on 2.4.3 until you are ready for me to test.

**Comment by earlSt1** [comment]
Hi, sorry for the wait but are you still getting this issue on the latest version of CF?

**Comment by Jonwh25** [comment]
Close this out. It was a problem due to being able to dig down with folders too far prior to this version. I redid the folder structure with the new version and no problem.

**Comment by earlSt1** [comment]
Ahh good to hear :smile:
