### ISSUE TITLE
Console error on startup

### ISSUE THREAD

**Issue by rverboom** [earlSt1/vtt-compendium-folders#145]
On startup I see an error in the console. 
![image](https://user-images.githubusercontent.com/9274945/171552880-2f3a8505-7671-49bc-b15a-42f868ec4ada.png)

I am unable to delete world compendiums or change visibility on any compendiums. If I disable Compendium Folders it seems to work fine again. 

I am using the latest stable foundry Version 9.268
Pathfinder 2e - 3.10.4.11747
And Compendium Folders 2.4.5

**Comment by earlSt1** [comment]
Thats a new one. It looks like you dont have a Default folder created. Ill provide you with a macro to create you one shortly

**Comment by earlSt1** [comment]
Try this as a macro then refresh the world:
```js
let allFolders = game.settings.get('compendium-folders','cfolders');
allFolders.default = {
    compendiumList:[],
    titleText:'Default',
    _id:'default',
    colorText:'#000000'
}
await game.settings.set('compendium-folders','cfolders',allFolders);
```

**Comment by rverboom** [comment]
That seems to have gotten rid of the error and the compendium window now has stuff nicely organized. 

Not sure how it got into that state, but I am sure it was me doing something... 

Thanks very much for the quick help :)
