### ISSUE TITLE
moving item throws exception and collapses all folders

### ISSUE THREAD

**Issue by wmve** [earlSt1/vtt-compendium-folders#148]
steps to reproduce

1. open a compendium
2. drag an actor from one folder to another, or from folder to the folder above (or root of compendium)

expected result: actor moves folders; folders that are open stay open

actual result: actor moves folder; all folders closed; exception appears in console log

i've tested this with multiple compendia.

here's the error i get.

![image](https://user-images.githubusercontent.com/55966777/174334893-9a76a87d-e8ee-4330-9d95-21800457920b.png)

**Comment by wmve** [comment]
btw, i turned off all modules apart from libWrapper to test and reproduce this.

![image](https://user-images.githubusercontent.com/55966777/174335832-383251f2-8bc9-4c23-b808-a79f3375a384.png)

**Comment by earlSt1** [comment]
Hi, since this is the same as the other error you posted I'll continue in issue #147 and close this one
