### ISSUE TITLE
TextEditor.getDragEventData is not a function

### ISSUE THREAD

**Issue by Cardagon** [earlSt1/vtt-compendium-folders#150]
When I try to use drag and drop functionality (either re-ordering compendium items or simply dragging and dropping an entity into a compendium) I get the following errors in the console. I can still export folder structures to the compendium, but if I try and drag and drop a single entity into a compendium nothing happens and I get this error.

![image](https://user-images.githubusercontent.com/67291426/176535164-de38e037-13f7-463b-be55-117b7ded2247.png)

**Comment by earlSt1** [comment]
Hi, can you make sure you are on the latest FoundryVTT version? Any version above v9 b269 should fix this

**Comment by Cardagon** [comment]
Good call! Just updated to 9.269 and am no longer getting that error and drag and drop is working as expected, awesome! Thanks for the quick reply!
