### ISSUE TITLE
BUG: Deleting folder from wrong compendium

### ISSUE THREAD

**Issue by farling42** [earlSt1/vtt-compendium-folders#154]
Foundry: 9.269
Compendium Folders: 2.4.6

To reorganise my game folders I manually duplicated a compendium pack in a module. ("Rules" is the original pack, "Players" is the copied version of the pack) by using the command-line (while no world was open).

I then started Foundry and opened the Rules compendium first, then I opened the Players compendium.

I then went back to the Rules compendium window and selected the "Descriptors" folder and selected Delete folder followed by Delete All.

The folder was actually deleted from the Players compendium window - not the Rules compendium window!

Closing the world and reopening it definitely shows that the folder was deleted from the Players compendium.

**Comment by farling42** [comment]
As long as I don't open a second compendium window, the folder deletion seems to work from the correct compendium pack.

**Comment by farling42** [comment]
I've just noticed that opening a second compendium window prevents the Import Folder working in the first opened compendium window.
In fact, opening a second compendium window makes no commands work in the first compendium window - even if the second window is closed, interactions in the first window (the only one still open) seem to be directed to the compendium that had been open in the second window.

**Comment by earlSt1** [comment]
Hi, just tested locally and this seems to be a bug with having 2 or more compendiums open. (the second compendium you open will be the one that is affected). I'll look into including a fix for this in the v10 version, in the meantime as a workaround you can open the Players compendium first, then the Rules compendium, and it should only modify the Rules compendium.

**Comment by earlSt1** [comment]
Turns out this was quite a simple fix, so I will push a hotfix out for v9 too

**Comment by earlSt1** [comment]
Fixed in v2.4.7 onwards
