### ISSUE TITLE
Create Macro menu entry not available in Macro Compendium

### ISSUE THREAD

**Issue by derekstodghill** [earlSt1/vtt-compendium-folders#162]
I created a Macro Compendium and then added a folder. When I try to add a macro to the folder, it has a menu entry for "Create RollTable" instead of "Create Macro". The workaround is to disable Compendium Folders module and add the macro to the compendium. Then enable Compendium Folders and add macros in compendium to folder. Foundry Version is 10 - Build 284 and Compendium Folders version is 2.5.2. 
![image](https://user-images.githubusercontent.com/68213422/188321274-94d8b05e-f20e-4ed1-bc5a-45968e99e460.png)

**Comment by earlSt1** [comment]
Hi, I responded to your discord message about this: 

> This button creates a roll table for all entries in a compendium folder. You cant directly create documents in the compendium, you need to drag a macro from your world into the compendium or export a folder structure
