### ISSUE TITLE
Error when enabled in pf2e

### ISSUE THREAD

**Issue by esheyw** [earlSt1/vtt-compendium-folders#163]
PF2E 3.13.6 (current)
Foundry 9.280
Compendium Folders 2.4.7 (current as far as the v9 updater knows)

only CF and libwrapper (1.12.8.0) active, I get the following error:
https://i.imgur.com/WkD38HU.png

Understood if this is wontfix because v9, but some of us are going to be on it for a while yet.

**Comment by earlSt1** [comment]
Fixed in v2.4.8
