### ISSUE TITLE
v10.285 Can't Create New Compendiums

### ISSUE THREAD

**Issue by Don-Pokoton** [earlSt1/vtt-compendium-folders#165]
Great work, this module has been a great help to me and my group. 

As per the release of V10.285, having this mod enabled, and proceeding to create a new compendium, the categories all become "undefined", and since a compendium category can't be undefined, the creation process stops.

**Comment by earlSt1** [comment]
Hi, that sounds weird, what system + version are you using?

**Comment by earlSt1** [comment]
I've just had a few more reports of this, i've got a fix that i'll release later today.

**Comment by earlSt1** [comment]
Fixed in v2.5.3
