### ISSUE TITLE
Warning messages with v2.5.3 under v10

### ISSUE THREAD

**Issue by manfred7168** [earlSt1/vtt-compendium-folders#170]
I see warnings in the log about compatibility issues within module.json:
setup.js:145 
        
       [compendium-folders] The module "compendium-folders" is using "author" which is deprecated in favor of "authors"
#logPackageWarnings @ setup.js:145
setup.js:145 
        
       [compendium-folders] The module "compendium-folders" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
#logPackageWarnings @ setup.js:145
setup.js:145 
        
       [compendium-folders] The module "compendium-folders" is using "name" which is deprecated in favor of "id"
#logPackageWarnings @ setup.js:145

**Comment by HippyCraig** [comment]
I updated to v286 and see the following

![image](https://user-images.githubusercontent.com/17074456/192151991-cf3ae3b6-76f6-4d5f-a940-72d61bfb7d6c.png)

**Comment by steveculshaw** [comment]
Weird ... I just get the three that @manfred7168 detailed

**Comment by earlSt1** [comment]
Fixed in v2.5.4

**Comment by HippyCraig** [comment]
Cool thanks!
