### ISSUE TITLE
Exception generated when opening new SWADE compendiums

### ISSUE THREAD

**Issue by aedgaruk** [earlSt1/vtt-compendium-folders#175]
Hi,

Since my update to FVTT v10 I'm logging these errors (see image):

![image](https://user-images.githubusercontent.com/111492074/194092370-a2b5e450-73b6-4739-b40a-2cab1bbc1dff.png)

... the module seems to be working OK but I mention it because a) wasn't doing it before v10 and b) they're in RED!! :)

Cheers
Andy

**Comment by earlSt1** [comment]
Hi, looks like this is preventing the Create folder in compendium button from appearing. Which system are you using?

**Comment by aedgaruk** [comment]
FVTT v10.286
SWADE v2.0.5
Compendium Folders 2.5.3

**Comment by earlSt1** [comment]
I know Swade recently dropped their CF dependency, but i havent checked it out yet. Just updating my local version now

**Comment by earlSt1** [comment]
Ahh it looks like they have their own interface for browsing the compendium, which trips up CF. It's nothing to worry about but i will look into getting rid of that error in the code.

**Comment by aedgaruk** [comment]
You Sir, are a Scholar and a Gentleman ...

![image](https://user-images.githubusercontent.com/111492074/194132748-e11d0352-ec05-490a-b754-f039023432a5.png)

... I leave this in your capable hands.
Cheers
Andy

**Comment by earlSt1** [comment]
Hi, in v2.5.4 I've added a new option which Disables folders inside compendiums. With this enabled you shouldnt see this error anymore.

**Comment by aedgaruk** [comment]
Retested and all good to go.

Nice one, Thank You :)
