### ISSUE TITLE
Cannot drag folder to another folder

### ISSUE THREAD

**Issue by EmmaEmmaEmma2** [earlSt1/vtt-compendium-folders#178]
Hello,

Using 10.287, I'm able to drag a subfolder from a folder to the main directory without issue, but when attempting to do the reverse, move a folder to be inside a different folder, nothing happens. As a result, my directory tree is becoming increasingly borked.

![image](https://user-images.githubusercontent.com/32316785/195000926-e6186e8b-0726-4e82-a53f-5e9f896b0210.png)

 I don't see any errors or anything popping up, is there any additional info I could provide that would help? I've tried with just Compendium folders and libWrapper active

**Comment by EmmaEmmaEmma2** [comment]
a possible workaround might be to drag the compendium files to actors, then export the folder structure back, but I haven't tried that yet

**Comment by earlSt1** [comment]
Hi, sorry for the wait. I think I've solved this in my testing branch and will look to push a release in the coming days.

**Comment by earlSt1** [comment]
This should be fixed in v2.5.4, so will close for the time being. Feel free to reopen it if you are still having issues with it.
