### ISSUE TITLE
Missing zip for v2.5.4

### ISSUE THREAD

**Issue by steveculshaw** [earlSt1/vtt-compendium-folders#179]
Foundry flagged an update to 2.5.4 as being available, but when I try to update, I'm getting an error about a missing "2.5.4.zip" 
Tried a few times with no joy  :-(

![image](https://user-images.githubusercontent.com/64320/195853321-2f5b2ef7-e4b9-43f3-a72d-643b051d7459.png)

**Comment by steveculshaw** [comment]
Marvellous ... after getting around to reporting the issue, I try again, and it works fine!!!

**Comment by earlSt1** [comment]
Haha you must have tried to update just as I was writing up the release notes :smile:

**Comment by steveculshaw** [comment]
:-)
