### ISSUE TITLE
Importing DDB Items > Weapons fails

### ISSUE THREAD

**Issue by Vralek** [earlSt1/vtt-compendium-folders#180]
When importing all from DDB Importer compendium it fails.
I've narrowed this down to the Weapons group. It forces the page to reload completely when it fails so I cant get an error log.

**Comment by Vralek** [comment]
![CF Error 1](https://user-images.githubusercontent.com/90917755/195891069-08d306f9-7f7d-4ec2-be81-6cc87e30b6c8.png)

**Comment by Vralek** [comment]
Foundry version: 10.288
5e version: 2.0.3
DDBI version: 3.1.15
Compendium Folders version: 2.5.3

**Comment by earlSt1** [comment]
Hi, could you try again with the version i released today? (v2.5.4)

**Comment by Vralek** [comment]
> Hi, could you try again with the version i released today? (v2.5.4)

Updated. Deleted failed import folder.
Re-imported, same thing.
![CF Error 2](https://user-images.githubusercontent.com/90917755/195926208-ee14aeb9-1ff8-44ca-83f7-cc8356c99c12.png)

**Comment by earlSt1** [comment]
Righto, will have a look into this tomorrow, just wanted to check I didn't accidentally fix it :smile:

**Comment by Vralek** [comment]
> Righto, will have a look into this tomorrow, just wanted to check I didn't accidentally fix it 😄

Sure thing, if you need, I'd be happy to test any fix you put out. This is a fresh install of everything and something I thought about is it could be a libwrapper issue as it has some warnings.

**Comment by earlSt1** [comment]
Hmm, I just tried on a fresh DDBI version, re-munched the items, and imported the weapons folder, and it appears to be fine. You could try remunching - maybe something went wrong during the initial munch??

**Comment by Vralek** [comment]
> Hmm, I just tried on a fresh DDBI version, re-munched the items, and imported the weapons folder, and it appears to be fine. You could try remunching - maybe something went wrong during the initial munch??

I got it to work but I first did a Compendium Folder Migration on Items before re-munching and importing the compendium. 
I guess resolve the bug?
