### ISSUE TITLE
Can't put items in compendium folders anymore.

### ISSUE THREAD

**Issue by sevrick** [earlSt1/vtt-compendium-folders#182]
Can't put items in compendium folders anymore. I can put them into the compendium but not folders. I am using the Star Wars FFG system if that matters.

**Comment by unmasSk** [comment]
Me too, after update, i cant put items in created folders. Im using DnD5e

**Comment by dutchcolonial** [comment]
Same here, after the updated not able to put anything in folders inside compendium. Using DnD5e v2.03 on Foundry v10 v10.288

**Comment by earlSt1** [comment]
Hi, sorry about that, will look into it later today.

**Comment by earlSt1** [comment]
Should be fixed in v2.5.5. Will close for the time being but feel free to reopen if its still around
