### ISSUE TITLE
Update CF version data on Foundry admin page

### ISSUE THREAD

**Issue by gizmo2342** [earlSt1/vtt-compendium-folders#198]
Hi.
The last version that is registered on foundry admin page is 2.5.0.
Could you please update the module page to make Foundry aware of the more recent versions.

If I set a requirement in my modules that requires a version newer than 2.5.0, Foundry comes up with a warning that the requirement cannot be fulfilled. In the end it will be fulfilled, but Foundry only knows after installation. This might confuse users.

Thanks in advance.
Martin
(Ulisses Spiele)

**Comment by earlSt1** [comment]
Hi, sure sorry I tend to forget unless its a major fvtt release. I'm gonna be pushing a release soon so will update it when i do that

**Comment by earlSt1** [comment]
Updated with latest version now, will try to keep on top of this
