### ISSUE TITLE
Enhancements: UI improvement

### ISSUE THREAD

**Issue by apoapostolov** [earlSt1/vtt-compendium-folders#2]
The Settings button on the right side of each compendium folder is not vertically centered. Also, the two borders nested in each other is UI different from one border only for all other folders used elsewhere in Foundry and doesn't look very modern UI-like. 

![image](https://user-images.githubusercontent.com/4083812/88479328-f99a5680-cf56-11ea-832d-75faf3f7f484.png)

Compare with how Folders look elsewhere. The icon int the right is vertically centered and there's no inner border with two colors only one.

![image](https://user-images.githubusercontent.com/4083812/88479352-2d757c00-cf57-11ea-9c5d-fd02f3301948.png)

There's also the issue that clicking the Gear button for settings does nothing at the moment.

**Comment by earlSt1** [comment]
The settings button currently doesn't do anything, but the border around the box should not be there. Is this persistent across multiple reloads?

If so, could you send me a list of the modules you are using? Perhaps there is some conflict between them.

**Comment by earlSt1** [comment]
After working through the issue with @apoapostolov we've found a compromise for this is to add the following rule to the Custom CSS module:

`#compendium h3 {border: 0px !important;padding: 0px !important;background: none !important;}`

**Comment by earlSt1** [comment]
Styling mentioned in previous comment added in v0.1.4. Closing issue.
