### ISSUE TITLE
V11 Unable to move any compendium inside or outside folders

### ISSUE THREAD

**Issue by remib1994** [earlSt1/vtt-compendium-folders#211]
Hello,
 I just migrate to V11 and I can't move any compendium in or out of any folder and new compendium cannot be moved too.
I don't know if you can't help me.

I tryed creating new folder but i don't even have the option, it's like the module is disable but it's actually up to date.

![image](https://github.com/earlSt1/vtt-compendium-folders/assets/22970652/69d611f0-8342-42ea-be80-e57a31ffc4cd)

Thank for you help.

**Comment by earlSt1** [comment]
Hi, so in v11 the module only migrates any CF folders into core Foundry folders. Once that migration is done the module is effectively disabled, letting core take over. I don't plan on introducing any CF features that have not been absorbed by core into v11, if you are talking about the edit dialog for folders

**Comment by remib1994** [comment]
So if I'm unable to move any compendium, drag them to folder is because of fvtt 11 and not cf ? 

Seem weird I can't move anything.

**Comment by earlSt1** [comment]
You should be able to drag/drop in v11. Is it still like that if you
disable CF?

**Comment by remib1994** [comment]
Yes i tryed with or without CF and i got the same problem. I even create new folder but i still can't move.

**Comment by remib1994** [comment]
Problem solved i reinstall my foundry, restart and delete the module. Now i can move my folders. 
Thank.
