### ISSUE TITLE
Migration fails due to exhausting system memory

### ISSUE THREAD

**Issue by FrankIsAtank** [earlSt1/vtt-compendium-folders#215]
The migration to v11 caps a CPU and eats up memory until it reaches 100% after about 5 minutes, then the tab crashes.
My system has 32 GB.
Hard to imagine why a migration needs that much memory.

**Comment by thejoester** [comment]
Yeah I have 64GB and its the same thing

**Comment by earlSt1** [comment]
Hi, is this a sidebar migration or migrating a compendium?

**Comment by FrankIsAtank** [comment]
> Hi, is this a sidebar migration or migrating a compendium?

Unsure. Whichever migration occurs when you click the button on the new Professor Farnsworth popup that appears when you login.

**Comment by earlSt1** [comment]
Can you both send me the contents of the Import/Export dialog in the module settings? I'm mainly interested in the Export side

**Comment by gludington** [comment]
Different person, but similar issue.  Attaching my  
[compendiumfolders.json.txt](https://github.com/earlSt1/vtt-compendium-folders/files/12063272/compendiumfolders.json.txt)

I have quite a few compendiums, both from modules and my own, and I will see many hundreds of thousands of
10250foundry.js:616 Foundry VTT | Registered callback for renderCompendiumDirectory hook

before the tab finally gives up.  I have been reloading when this happens, and it appears to pick up where it left off, though I am not sure if there is any damage yet to whatever compendium was in progress at the time of the tab crash.

**Comment by earlSt1** [comment]
Thanks, will check it out in a bit. In the console there may be more clues
as to where its failing if you show verbose logging. In chrome there should
be a dropdown button where you can select log levels. It says Default by
default i think.

**Comment by gludington** [comment]
Those lines were from the verbose section of the logs.  If I skip migration and go check out the "Configure Settings" section, it only shows two of my compediums as present in as migration options, though it starts with the (admittedly) large Baileywiki modules each time, and I seem unable to get past that.

**Comment by earlSt1** [comment]
Ok, i'm a bit confused, so the Sidebar migration button (when you click on the popup window when you first launch the module), is the one generating those log messages. That migration doesnt actually touch the contents of the compendiums, its just the sidebar folders. The section in the module settings is for migrating folders inside each compendium. Also compendiums will only show in that settings dialog if they are unlocked, as I'm not able to modify them if they are locked. 

I just tested your sidebar config in my test world, and it seemed to migrate and create the folders fine. Do you have any other modules enabled that could be interfering with the migration?

**Comment by gludington** [comment]
Interesting.  It may be a false positive then, in that the last element I see in the UI is that folder migration has started before I get hundreds of thousands of those hook messages in console, and the browser eventually halts.  If I disable *EVERY* module, migration appears to succeed.  After re-enabling the modules, the world loads again, though the sidebar has a large number of duplicates (e.g. I have 15 "Actor" folders, 12 "Item" folders, and so on, each with different (or sometimes no) contents, presumably from the browser dying mid-migration, for whatever cause.

**Comment by ref2335** [comment]
Same issue here, encountered similar results with Edge and Firefox browsers.

**Comment by Nedrapter** [comment]
Also experiencing the same, upgraded today to v11 306 and migration crashes the browser tab, even with 64gb RAM. I do have other modules enabled but, many of them might be having folders that need migration too, so I'm not sure whether makes sense disabling randomly (I have lots of modules, compendium and folders).

**Comment by thejoester** [comment]
Honestly I just gave up, uninstalled the module, and manually rebuilt all my compendiums.

**Comment by Nedrapter** [comment]
> Honestly I just gave up, uninstalled the module, and manually rebuilt all my compendiums.

Wish I could do the same, but I've been building folders for like 2 years...and some 3rd part content creators have compendiums with 250+ folders....

Update:
Checking out the console, even after page crashes, these counters keep going 
![image](https://github.com/earlSt1/vtt-compendium-folders/assets/74311190/a1df31e4-40a9-4d3c-a20a-4df1a3cdee81)

And looking at the Task Manager the RAM doesn't reach 100% or even close, but still the page crashes, saying that it ran out of memory.

**Comment by earlSt1** [comment]
> > Honestly I just gave up, uninstalled the module, and manually rebuilt all my compendiums.
> 
> Wish I could do the same, but I've been building folders for like 2 years...and some 3rd part content creators have compendiums with 250+ folders....
> 
> Update:
> Checking out the console, even after page crashes, these counters keep going 
> ![image](https://github.com/earlSt1/vtt-compendium-folders/assets/74311190/a1df31e4-40a9-4d3c-a20a-4df1a3cdee81)
> 
> And looking at the Task Manager the RAM doesn't reach 100% or even close, but still the page crashes, saying that it ran out of memory.

Hi, just to clarify this is after clicking the sidebar migration? (The button on the popup window with professor farnsworth when you first boot up in v11)

**Comment by earlSt1** [comment]
Another thing to try is not having the compendium sidebar visible when doing the migration (so stay on the actors tab for example). It may skip trying to render the directory which looks to be the problem

**Comment by Nedrapter** [comment]
> 

Just tried that, but it had no effect.

**Comment by earlSt1** [comment]
> > 
> 
> Just tried that, but it had no effect.

Ok, will try and find some time to check this out today.

**Comment by earlSt1** [comment]
Alrighty, I've managed to replicate this issue by enabling the module **Compendium Browser**, disabling this module allows me to do the sidebar migration successfully. Can you try with disabling this module if you are using it? If you're not can you send your module list and system?

Either way, if you disable all modules other than content modules (which just have compendiums in them), and CF + libWrapper, then it should work fine.

**Comment by Nedrapter** [comment]
It is working now, indeed!
Is there a way to migrate all unlocked compendiums' folder data in one go?

**Comment by earlSt1** [comment]
> It is working now, indeed!
> Is there a way to migrate all unlocked compendiums' folder data in one go?

Great! And no unfortunately, i had a feeling that if i added that option people would run into memory issues again. You can call the migration code using a macro, so you could try batching them in groups of 5 or 10, but its more reliable to do them one by one. 

See this comment for an example macro: https://github.com/earlSt1/vtt-compendium-folders/issues/208#issuecomment-1568141857

**Comment by earlSt1** [comment]
I'll be closing this issue for now, as it's likely that a lot of these issues have stemmed from the Compendium Browser module being enabled.

For anyone else encountering this issue, disable Compendium Browser before running any migrations. Once the migrations have been done you can safely reenable it.
