### ISSUE TITLE
Import/Export question

### ISSUE THREAD

**Issue by Nedrapter** [earlSt1/vtt-compendium-folders#218]
Might not be in the scope of this module anymore, but I figured you might be the best person to ask. Is there a way to import/export or copy the folder structure from one world to another for non-tech savvy users? Before v11 I was using CF in conjunction with Forin's Copy Environment and it was copying CF's settings and compendium folder structure along with all other module settings. Now that folders are part of the core function, it doesn't get included in that module. I tried ti inherent Import/Export CF has but also that doesn't pick up anything from the new "core" folder structure.

And one more side question: Is there a macro that can delete all the CF_Folder Backup folders that remained after the cleanup?

**Comment by earlSt1** [comment]
Hi, the macro wizards in the discord might be able to come up with something similar to what CF did with core sidebar compendium folders, but CF doesnt really know about core folders, it just creates them based on old CF folders. 

Thinking about it, if you had your old Import/Export string from before you migrated to V11, you could create a new world, import that string into CF, then do the sidebar migration and it should create the folders for you. Not the most ideal way of doing it but if you had a lot of folders it would save a lot of hassle

There is an option in the module settings called Cleanup Compendium which will clear all old CF data from a compendium. It wont remove the CF_Folder backup folder though, so youll have to remove that manually (a macro could easily look thru folders in a compendium based on the name and remove them)

**Comment by Nedrapter** [comment]
Thank for the swift reply!
Sadly I don't have the old and I reorganized everything after upgrading...
CF has been core part of my foundry and everything would have been so messy without it! Thank you for your awesome contribution to many people's Foundry experience!
