### ISSUE TITLE
Journal Entries placed on Scenes become dead links when moving to Compendium. Is there a way to preserve those links?

### ISSUE THREAD

**Issue by jacobjorvang** [earlSt1/vtt-compendium-folders#23]

**Comment by earlSt1** [comment]
I've just tried to replicate this by making a scene, adding a journal entry to it, exporting it to a compendium using the Export icon, then re-importing it and viewing it. I can see the journal entry icon on the map and it links just fine (i even moved the journal entry into another folder and repeated the proceess).

Could you detail the steps you are taking to create these dead links? I havent had a chance to play around with how scenes interact with compendium folders

**Comment by jacobjorvang** [comment]
Heh, yeah I don't really know myself if this is a new feature or a bug report, but it's not working for me either way. Just made a new test world, copied over the packs directory and added the db files to the new world.json. Enabled the folders modules, imported journals, imported scenes. Map notes show as Unknown and unlinked. I was hoping to use the module for storing the books/chapters I have created but are not currently using, but I can't really since I use map notes extensively, so it would be cool if this feature was added. But I have no idea how much of that would be in the domain of FVTT core, so maybe it's an unreasonable ask 🤷‍♂️

**Comment by earlSt1** [comment]
So from what i've tested, the map notes only link to journal entries in the current world. If you export them and import them to a new world the link breaks somewhere. Looks like this is a core foundry limitation, and im not sure about how the links work.

Ideally you should be able to link map notes to journal entries in compendiums, not sure if theres a module which allows this yet. You can get around it by double right clicking the Unknown tag and changing the Journal entry at the top to point to your chapter in the current world, but that sounds like quite a long process :)

**Comment by jacobjorvang** [comment]
If you knew how many map notes I have... 🙂

I have made a feature request to core. I guess we’ll see what happens.

**Comment by earlSt1** [comment]
Awesome, I'll close this issue then as I cant really help any more. Maybe someone has made a macro or something which imports stuff in the discord? If not you could try the Adventure Exporter module, or Easy Exports.
