### ISSUE TITLE
Folder colour is only respected when there are no subfolders

### ISSUE THREAD

**Issue by M0nk3yy** [earlSt1/vtt-compendium-folders#24]
It would be nice if their colour info could be retaind too

![image](https://user-images.githubusercontent.com/66137312/99657504-24547180-2a56-11eb-9a16-e0b6d0c26991.png)

**Comment by earlSt1** [comment]
Hi, so folder data is saved into the actor data. The folder colour will show up if you have an actor in the folder, if there are no immediate child actors for the folder, then it will use the default colour (which is black).

You can use a temporary actor and place it in the Armour/Shields/Weapons directory, and you will be able to change the colour + name of the folder

**Comment by earlSt1** [comment]
Feature now implemented in v2.0.8
