### ISSUE TITLE
Bulk Import Error

### ISSUE THREAD

**Issue by manuel-leveugle** [earlSt1/vtt-compendium-folders#25]
Hello, an error is present during a grouped import from a compendium, the creation of asynchronous folder does not work and sometimes the same folder is sometimes created several times.
Compendium tree:
![image](https://user-images.githubusercontent.com/52576910/99863251-8e2b6300-2b9d-11eb-8006-c5116e32f6f7.png)

Import Tree:
![image](https://user-images.githubusercontent.com/52576910/99863274-b0bd7c00-2b9d-11eb-9477-cc18d0d2ddc2.png)
So here in the first subfolder a/a.a/c we have part of the objects and in the second subfolder a/a.a/c is the other part.

in addition, it is not a bug, but I include it in this ticket in case, a small evolution would be the posibility to add a parameter in the options of import to force the overwriting if an object already exists.
Thanks you.

**Comment by earlSt1** [comment]
I thought I fixed the duplicate folders on import bug, looks like I haven't. I'll look into fixing this for next release.

As for your second suggestion I do like it, having an option like Merge by name on the Export process would be a good improvement.

**Comment by earlSt1** [comment]
So the bug with duplicate folders *should* be fixed in v2.0.5

I've also added a simple version of your suggestion (merge-by-name tickbox for Importing)
