### ISSUE TITLE
Creating errors converting locked compendiums

### ISSUE THREAD

**Issue by Avitale34** [earlSt1/vtt-compendium-folders#27]
The newest update causes a bunch of error messages about failing to convert locked compendiums. Not game breaking but kinda annoying.

**Comment by earlSt1** [comment]
Gah, that was an oversight writing the conversion code. I'll fix this very soon (along with the rolltable issue)

**Comment by earlSt1** [comment]
This should be fixed in v2.1.0, if you're still having issues pop a message here and i'll reopen the issue
