### ISSUE TITLE
*User* lacks permission to update the World setting compendium-folders.converted-folders

### ISSUE THREAD

**Issue by NateHawk85** [earlSt1/vtt-compendium-folders#28]
Upon loading into the game, our players are receiving the following error message: "User *user* lacks permission to update the World setting compendium-folders.converted-folders". This happens to every user other than the GM whenever they log into the world.

**Comment by earlSt1** [comment]
I have just this minute released a hotfix for something else, which should fix this issue. Can you try updating and check with v2.1.0?

**Comment by earlSt1** [comment]
Spoke to Nate on discord, he's confirmed this has been fixed in v2.1.0
