### ISSUE TITLE
Lag when searching in a compendium

### ISSUE THREAD

**Issue by achhandrian** [earlSt1/vtt-compendium-folders#31]
When Compendium Folders is active there is a noticeable lag when you open a compendium and start searching for something,
the bigger the compendium the harder the lag.
Version of foundry is 0.7.7.
system is dnd5e version 1.1.1
module version 2.1.2
no other module active except compendium folders

**Comment by earlSt1** [comment]
Hi, is this in any compendium or just compendiums with folders?

**Comment by achhandrian** [comment]
I use the compendium folder only to make a folder in the compendium overview, don't have folders in the compendium itself.
so i would say any folder.

**Comment by earlSt1** [comment]
Fixed issue in v2.1.3
