### ISSUE TITLE
Exporting to compendium generates garbaged entry in top of each list

### ISSUE THREAD

**Issue by r-valyar** [earlSt1/vtt-compendium-folders#32]
**This is only when a compendium is opened by **player**!**

When I export folder or folder structure to compendium, everything looks good until a player logs in and opens the compendium. There is such entry as in the image below in the top of every folder and sub-folder. The screenshot is from the Wrath & Glory system if this might matter. Haven't tested with other as I don't have any.

![image](https://user-images.githubusercontent.com/63558984/100599782-1f6ea800-3309-11eb-98f7-e9839c79ce1f.png)

**Comment by earlSt1** [comment]
Ah i missed this in testing. the code that hides those entities only runs for the GM. I'll push a hotfix soon which resolves this :)

**Comment by earlSt1** [comment]
Fixed in v2.1.4

**Comment by Honkou** [comment]
Hi, not sure it's fixed. Whenever I try to export data to a compendium, I get this:
![image](https://user-images.githubusercontent.com/73638904/102382656-f6b60600-3fca-11eb-8c97-45f225b2b173.png)
with this error in the console:
![image](https://user-images.githubusercontent.com/73638904/102382726-0afa0300-3fcb-11eb-9214-cc3d7aeb91c8.png)
It was on a gm account.

**Comment by earlSt1** [comment]
@Honkou Just made a new issue for that, thanks for reminding me i'll check it out soon
