### ISSUE TITLE
Query values are persisted across all compendiums

### ISSUE THREAD

**Issue by esb** [earlSt1/vtt-compendium-folders#36]
When a query filter is set for a compendium, then same query is applied to all compendiums that are opened subsequently. This is very confusing, as it looks like the function is broken as the compendiums will often show no data at all with the filter in place.

The filter is saved in the 'last-search' module setting which means it is persisted across game restarts, which can lead to even more confusion because it can hide all the entries if you don't notice that the search is still present.

I'd suggest that this behaviour is not intuitive, and the search filter should only apply to the compendium for which it was originally used. The filter should also be cleared on system restart.

**Comment by earlSt1** [comment]
I thought I made it so the search term cleared whenever a new compendium was opened. I'll have another look at it soon thanks for pointing it out.

**Comment by earlSt1** [comment]
Feature included in v2.1.8. Closing for now
