### ISSUE TITLE
[Suggestion/Question] Make the module easier to integrate with another compendium modules

### ISSUE THREAD

**Issue by lipefl** [earlSt1/vtt-compendium-folders#39]
I build my own compendium modules to use in my games. And i'd like to set it pre-configured in the compendium folders? Is that possible?
I see that the Official Savage Worlds module use it, but in a complex way (adding a path variable to each item).
An easier way would be to accept a variable, maybe a json to configure paths, like the import/export function.

**Comment by earlSt1** [comment]
Hi, sure it's fairly simple to setup compendium folders for your own shared modules. All you need to do is export a folder structure to a shared compendium (or any compendium in a module that you have), using the compendium folders export button next to each folder. 

I've got a gif of me exporting some items to a compendium on the readme page. You just need to make sure that there is a compendium that exists and is unlocked.

While I do like the idea of having a block of json to define folders and stuff, I can't see it being that easy to implement. My current approach of saving folder data inside the compendium ensures that the folder data is transferrable between worlds (and even users).

**Comment by lipefl** [comment]
I think i get it. I saw the gif, but i was trying to find these buttons on compendium, not on items tab. I'll try that. Thank You!
