### ISSUE TITLE
Bug: Folders (except Actor) Disappeared

### ISSUE THREAD

**Issue by Dumbhuman** [earlSt1/vtt-compendium-folders#4]
I just updated to 1.4 to do some tests and I've lost all of my folders except for the Actor folder (which won't open).  The compendiums all come back if I disable the Compendium Folder module, but with it enabled I only get this.
![image](https://user-images.githubusercontent.com/63615591/89154017-f5ec6e00-d51a-11ea-8c83-3001b27b74c3.png)

 As far as I can remember, this is what I did before reaching this state:

Created a compendium folder named Classes with a random purple color.
Created an item compendium named Fighter.
Edited the Classes compendium folder to include the Fighter compendium.

At this point, I first encountered the error of having only the Actor folder displaying in my compendium tab and it wouldn't expand to show its contents when clicked.  I disabled the module and allowed Foundry to refresh.  Then I enabled the module and after Foundry refreshed again I saw all folders including the Classes folder which now included the Fighter compendium.

I opened and closed some other folders.
I searched in contextual menus for a way to rename the Fighter compendium.
Then I deleted the Fighter compendium.
I created an item compendium named Maneuvers.
Then I honestly don't remember whether edited the Classes compendium folder again or if it was immediately after creating the Maneuvers compendium that I ran into the Actors only folder problem again.

I once again tried to disable and re-enable the module, but the Actor only problem persists.  It even persists after a restart of the Foundry VTT application.  I haven't tried a delete/reinstall of the module yet.

**Comment by earlSt1** [comment]
Hi, I also encountered a few issues while playing around. Creating compendiums confused the module as I had not accounted for this. You may find this will happen also if you enable/disable a module which adds/removes compendiums, and for players where a compendium is invisible to them.

I've tested some fixes and creating compendiums, in addition to adding/removing modules, works fine. This will be included in 0.1.5

**Comment by earlSt1** [comment]
@Dumbhuman please can you try updating the module and trying again? This should be fixed in v0.1.5

**Comment by earlSt1** [comment]
Issue fixed in v0.1.5
