### ISSUE TITLE
Feature Request: Drag to sort Folders in Compendiums.

### ISSUE THREAD

**Issue by DivertedCircle** [earlSt1/vtt-compendium-folders#42]
By default folders in a compendium sort alphabetically. I'd love the ability to sort manually by dragging folders.

**Comment by DivertedCircle** [comment]
An addendum to this, I'd love to be able to sort items within a folder as well, rather than have them default to alphabetical.

**Comment by geoidesic** [comment]
You can already sort folders manually by dragging folders. It works.
As for your second request, you just need to set `manual` sorting when editing / creating the folder.

**Comment by geoidesic** [comment]
Oh wait, I'm looking at Item folders. Never mind.

**Comment by apoapostolov** [comment]
This is working in 2.2.0 maybe good to close?

**Comment by earlSt1** [comment]
It is?! It shouldn't be, I havent touched the Folders In Compendiums code at all. 

Next releases will be focused on improving that area.

**Comment by DivertedCircle** [comment]
> 
> 
> This is working in 2.2.0 maybe good to close?
Definitely not working within compendiums.

**Comment by earlSt1** [comment]
Hi, sorry for the very long wait, but the good news is that I've finally managed to figure out a way to implement this and the feature needs a bit of testing (as well as some others).

If you'd like to test, you can install the test version using this manifest: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/09x-update/test/module.json
I **strongly recommend** backing up all your data first in case something breaks though

**Comment by earlSt1** [comment]
Implemented in v2.4.4
