### ISSUE TITLE
Hide folder for players if the folder only contains folders where all items are hidden 

### ISSUE THREAD

**Issue by Amuxix** [earlSt1/vtt-compendium-folders#43]
So currently if all compendiums inside a folder are hidden that folder is hidden for the players, however if a folder has a subfolder, the parent folder will always be shown, even if all items inside the subfolder are hidden.

Steps to reproduce:
1. Create folder.
2. Create a subfolder.
3. Add a compendium to the subfolder.
4. Hide the newly created compendium.

Expected behaviour:
The first folder should not be visible to players.

Current behaviour:
The folder is shown to players

Example:
GM View 
![image](https://user-images.githubusercontent.com/7691673/107213788-e0438e00-6a00-11eb-80f7-1c4220fc83f4.png)

Player View
![image](https://user-images.githubusercontent.com/7691673/107213841-f0f40400-6a00-11eb-8353-2cab1a1dcb6d.png)
Default 5e folder should not show for player

**Comment by earlSt1** [comment]
Sorry for the late response. I'm in the process of reworking the compendium directory code, and as a result this issue should be sorted in the next release.

**Comment by earlSt1** [comment]
Fixed in v2.2.0
