### ISSUE TITLE
String comparison of version numbers doesn't work with two digit versions.

### ISSUE THREAD

**Issue by MicahZoltu** [earlSt1/vtt-compendium-folders#47]
https://github.com/earlSt1/vtt-compendium-folders/blob/1ef18345c16cd4c973352340b97677466eaec2c5/compendium-folders.js#L3714-L3715

```
assert(('1.9.0' > '1.10.0') == true) // should be false
```

**Comment by earlSt1** [comment]
I realised this too when writing the version checking code, however when I checked foundry's version history they only seem to use 1 digit for major.minor.patch. Normally when Atro nears version x.y.10 he's on the next minor version. 

If a version change for 2 digits is announced in the future i'll jump on this asap, but for now I think it should be safe.

**Comment by earlSt1** [comment]
Closing for now, If Atropos announces an FVTT version with a 2 digit major/minor/patch number I'll reopen this issue and add it to my todo list.
