### ISSUE TITLE
Check is always true.

### ISSUE THREAD

**Issue by MicahZoltu** [earlSt1/vtt-compendium-folders#48]
https://github.com/earlSt1/vtt-compendium-folders/blob/1ef18345c16cd4c973352340b97677466eaec2c5/compendium-folders.js#L3714-L3715
https://github.com/earlSt1/vtt-compendium-folders/blob/1ef18345c16cd4c973352340b97677466eaec2c5/compendium-folders.js#L3757

The `hasFIChanges` will always be true, since the version is tightly coupled with this code.  Consider removing it and only retaining the `post073` check.

**Comment by earlSt1** [comment]
I included this check initially because when the folders in compendiums functionality was released, version 0.7.3 was not considered as stable, so people were still sitting on 0.6.5. 

Now we're nearing 0.8.0 I can safely drop the `hasFICChanges` variable. Thanks for reviewing my code btw :smile:

**Comment by earlSt1** [comment]
Fixed in v2.2.0
