### ISSUE TITLE
Mod sometimes doesn't load.

### ISSUE THREAD

**Issue by MicahZoltu** [earlSt1/vtt-compendium-folders#50]
I have been unable to come up with repro steps, but sometimes Compendium Folders fails to actually have compendium folders.  When it fails, I end up with *worse* than the default compendium, where I just kind of have one giant list of items with no folder structure at all.

Disabling Compendium Folders and then enabling it seems to resolve the issue.  I have been doing a lot of mod addition/removal, so my *guess* is that is what triggers it.

**Comment by earlSt1** [comment]
Fixed in v2.2.0
