### ISSUE TITLE
Minor issue - different font used on Create Compendium

### ISSUE THREAD

**Issue by apoapostolov** [earlSt1/vtt-compendium-folders#53]
![image](https://user-images.githubusercontent.com/4083812/112066302-c56f4800-8b6e-11eb-9ca3-663f178eabe0.png)

**Comment by earlSt1** [comment]
I think it's the same font used, just smaller. They should be side by side though. Are you on the latest version (v2.2.0)?

**Comment by apoapostolov** [comment]
They are in 5E systems. They are not in PF2. 5E system example below:

![image](https://user-images.githubusercontent.com/4083812/112068358-67446400-8b72-11eb-8338-d05ad2afdd82.png)

**Comment by earlSt1** [comment]
Huh, strange. I'm guessing the folders still render ok for PF2?

**Comment by apoapostolov** [comment]
Yes, no problems with the folders in pF2.

**Comment by earlSt1** [comment]
Closing issue as it seems the text is the same font, just a bit smaller to fit the longer text in.
