### ISSUE TITLE
API/Methode to translate folder names programmatically ?

### ISSUE THREAD

**Issue by sladecraven** [earlSt1/vtt-compendium-folders#55]
Hello, 
In the scope of a sub-module for SWADE, I need to translate the compendium folder names.
Is there an API available to change this ?

**Comment by earlSt1** [comment]
In the latest version (2.2.0) you can access a list of CompendiumFolder objects (derived from the Folder class), at `game.customFolders.compendium.folders`.

To update a name programmatically, you should be able to do
```js
let folderObj = game.customFolders.compendium.folders.get({folderId});
folderObj.name = "New Name";
// To save without refreshing the directory (useful if you're changing a lot of folders)
folderObj.save(false);
// Or if you want to force a refresh, you can just do
folderObj.save();
```

Like in the `game.folders` collection, you can search for folders with matching fields e.g
```js
let actorFolder = game.customFolders.compendium.folders.entries.find(f => f.name === 'Actor')
```

Let me know if you run into any issues. I've tried to design the collection to be as accessible as possible (replicating `game.folders`)

**Comment by sladecraven** [comment]
Thanks. I do not see the field `name` but `data.titleText`. It wworks for 1st level folders, but where are stored sub-folders inside compendiums itself ?

**Comment by earlSt1** [comment]
There should be a setter/getter defined which maps `folder.name` to `folder.data.titleText`.

Child folders are stored in `folder.children`, there should be a list of CompendiumFolder objects in there if a folder has children.

Similarly `folder.parent` will get you the parent CompendiumFolder for a folder.

**Comment by sladecraven** [comment]
OK, it starts to work for folders now :)
But i am facing also folder embedded inside compendiums. I see that data are stored in the flags.cf, but I did not found any easy way to translate it on the fly (like I ded with Babele). Do you have an idea/hint for this ?

**Comment by earlSt1** [comment]
So you can get a list of all folder objects in a compendium as they all have the same name `#[CF_tempEntity]`.

Therefore to get a list of entity ids of folder objects in a pack, you can use this.
```js
let pack = game.packs.get(packCode)
let folderEntityIds = pack.index.filter(x => x.name === #[CF_tempEntity]).map(e => e.id)
```
Once you retrieve an entity from the compendium, you can access the folder data and update the name like so:
```js
let folderEntity = pack.getEntity(id);
folderEntity.data.flags.cf.name = "New Name"
await pack.updateEntity(folderEntity);
```
(Make sure that the compendium is unlocked before updating)

**Comment by sladecraven** [comment]
I am afraid that flags cannot be updated that way (ie with updateEntity). I am searching other methods.

**Comment by earlSt1** [comment]
Thats weird. Are you getting any errors when doing so? 

If the compendium view isnt updating then it could also be a caching issue (try opening a different foldered compendium, then open the original one)

**Comment by sladecraven** [comment]
I found the proper syntax :  await pack.updateEntity({ _id: index._id, 'flags.cf.name': "Atouts Sociaux" } ); 
And also it seems there is a caching issue, yes
WIP :)

**Comment by earlSt1** [comment]
Closing for now, if you have any more questions feel free to add to this issue or open a new one :smile:
