### ISSUE TITLE
Duplicate Player Folder

### ISSUE THREAD

**Issue by Alexis-Grimm** [earlSt1/vtt-compendium-folders#59]
So I'm co-dming a oneshot and we have two GM users (Not sure if that's what's causing it or not, just thought I'd mention) and the compendium directory that contains the player accessible compendiums is duplicated for the player's, me and the other dm are not having this issue however the players are. When I load in as one of the players I also get the issue. The contents of the directory is same for both versions, so theres no real issue, its just somewhat annoying.

We're using Foundry 0.7.9
DND5e 1.2.4
Compendium Folders 2.2.1

![duplicatefolders](https://user-images.githubusercontent.com/23371612/112557281-80cbf280-8da2-11eb-84c2-7a7db43326fc.png)

**Comment by MrZwij** [comment]
I can recreate this by toggling visibility on a compendium within a subfolder. When "OGL Kobold Press Monsters" is visible, the player sees Actors twice. If it's not visible, only once. 

My Character Builder folder shows one duplicate for **every visible subfolder**. As you remove the visibility of the subfolders, the players see fewer duplicates.

(You can also see here that folder images don't display for players).

**Compendium visible**
DM view:
![image](https://user-images.githubusercontent.com/12764695/112733467-dc62c100-8f05-11eb-83fe-f6374434e809.png)

Player view:
![image](https://user-images.githubusercontent.com/12764695/112733561-4b401a00-8f06-11eb-828f-2c629ba9de0a.png)

**Compendium not visible**
DM view:
![image](https://user-images.githubusercontent.com/12764695/112733519-1a5fe500-8f06-11eb-8bba-bf0482695d40.png)

Player view:
![image](https://user-images.githubusercontent.com/12764695/112733540-2ea3e200-8f06-11eb-991c-7a6bb40c244a.png)

**Comment by earlSt1** [comment]
Wow that looks ... horrible 😆 Thanks for testing for me, i've been quite busy the past few days but tomorrow i can work towards fixing this.

**Comment by earlSt1** [comment]
Found the issue, it was only occuring if the parent folder (Actors in your case) had no compendiums in it. Can you both uninstall and reinstall using this manifest and check its been fixed?

I've also pushed a fix for the icons not visible for players if you could check that @MrZwij 

https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

**Comment by MrZwij** [comment]
Sorry, I'm TERRRRIBLE at checking email. Those fixes look good!

**Comment by earlSt1** [comment]
Fixed in v2.2.2
