### ISSUE TITLE
Just wanted to make you aware

### ISSUE THREAD

**Issue by HippyCraig** [earlSt1/vtt-compendium-folders#6]
I was on a very early 0.14 version, that would not auto update to the latest.  I had to uninstall and reinstall the module.  Just wanted to make you aware in case other users had the same issue.

**Comment by earlSt1** [comment]
Thanks for letting me know, others have reported the same. It's a bit finicky getting modules to auto-update but i'll aim to fix this in the next release

**Comment by earlSt1** [comment]
Should be fixed in v1.0.2 onwards (you will need to install 1 more time to get the right module.json file)

**Comment by HippyCraig** [comment]
Great thanks, really love the tool.   I have so many different compendiums it was a nightmare to manage, this makes it so much better.
