### ISSUE TITLE
Suggestion: please update the readme file and tutorial examples to reflect the new version

### ISSUE THREAD

**Issue by LotsOfLore** [earlSt1/vtt-compendium-folders#62]
Hi, after having updated to the new version I thought the module was bugged, as the gear icon was gone and I didn't know how to organize the content within each folder. Then I figured that functionality is now accessible via a different method: right-click > edit folder. No more gear icon. 
I suggest updating the tutorial images as I'm sure this may cause confusion. 

Thank you and keep up the great work!

**Comment by earlSt1** [comment]
Thanks for reminding me! Been meaning to do that but i forgot :smile:. Just updated the readme and images to reflect new changes.
