### ISSUE TITLE
Issue for non-gamemasters: User <User> lacks permission to update the World setting compendium-folders.cached-folder

### ISSUE THREAD

**Issue by bloy** [earlSt1/vtt-compendium-folders#66]
My users are getting the above message when trying to open a compendium from a module with folders. The compendium opens, but without folders and with the folder placeholder entries visible. The same compendium opens fine for me as a gamemaster.

Workaround: grant my players permission to modify configuration, which is not ideal.

![image](https://user-images.githubusercontent.com/1473405/114426468-ba14a880-9b7f-11eb-8421-934dde241b19.png)

**Comment by earlSt1** [comment]
Ah this was a result of changing the caching behavior. I'll publish a release shortly which fixes this.

**Comment by earlSt1** [comment]
Should be fixed in v2.2.4 if you update

**Comment by bloy** [comment]
Verified fixed in 2.2.4. Thanks!
