### ISSUE TITLE
Feature Request: Support for libWrapper

### ISSUE THREAD

**Issue by Tupsi** [earlSt1/vtt-compendium-folders#68]
I get lots of errors here on the user (read not GM) side having both TokenAttacher and Compendium Folders active. Wading threw both of your code it looks to me, like you are batteling for a hook called.

Hooks.on("getCompendiumDirectoryEntryContext", 

and as I understand the concept of libWrapper, this would be on option to resolve the conflict.

https://github.com/ruipin/fvtt-lib-wrapper
https://github.com/KayelGee/token-attacher

![image](https://user-images.githubusercontent.com/3730499/114841777-82ed0400-9dd8-11eb-8e66-eb0e1bb02c95.png)

**Comment by earlSt1** [comment]
I will be adding support for libwrapper, but i think this specific error is an implementation issue. I'll fix this in the next release.

**Comment by earlSt1** [comment]
So i've currently got 0.8.2 checked out and cant test the 0.7.9 fix. Would you mind uninstalling your current version and installing this manifest to see if it solves it?

https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

**Comment by Tupsi** [comment]
Will do and report back tomorrow after testing.

**Comment by earlSt1** [comment]
Included in v2.2.43
