### ISSUE TITLE
Failure to export scene structure into compendium

### ISSUE THREAD

**Issue by ABrandau** [earlSt1/vtt-compendium-folders#70]
Hey, tried two scenarios, in the first one I exported simple branch of scenes into a compendium, the process succeeded but the compendium does not read the folder structure, as seen on the image.

![image](https://user-images.githubusercontent.com/11763228/116794811-f7dd6080-aa9d-11eb-9503-e5fa3420b796.png)

![image](https://user-images.githubusercontent.com/11763228/116794825-20fdf100-aa9e-11eb-9c69-8a7b25c6ce30.png)

Exporting individually solves this issue but generates duplicates of folders that are already there, making it more comfortable to do the entire process once.

In other situations I had the exported fail completely (export nothing) and export but ignore the folder structure.

![image](https://user-images.githubusercontent.com/11763228/116794865-6fab8b00-aa9e-11eb-9f02-926874d1ea63.png)

**Comment by earlSt1** [comment]
Thanks for raising this. Scenes have always been the odd one out for exporting folder structures because my code needs to wait for the scene backgrounds to upload to the compendium.

I'll definitely look into this once i get the chance as the normal solution is to export a few scenes at a time, but that should merge the folders by name, and you have reported thats not the case.

**Comment by ABrandau** [comment]
Update, issue might be related to scenes with missing files, after checking the scenes a bit, i found one scene with an invalid background image address, after correcting that address and regenerating that thumbnail image, the export feature worked as it should.

**Comment by earlSt1** [comment]
> Update, issue might be related to scenes with missing files, after checking the scenes a bit, i found one scene with an invalid background image address, after correcting that address and regenerating that thumbnail image, the export feature worked as it should.

Haha what timing :smile:, I'll still keep this issue open as to remind me to work on the scene folder structure export improvements.

**Comment by earlSt1** [comment]
Merging into issue #44
