### ISSUE TITLE
Module not working after 0.8.6 update

### ISSUE THREAD

**Issue by EvldoaTV** [earlSt1/vtt-compendium-folders#75]
The folders no longer appear in the compendium after the recent release

**Comment by earlSt1** [comment]
Hi, are you getting any errors in the F12 console when you open your compendium?

**Comment by EvldoaTV** [comment]
Not that I can see the folders are just not showing up

**Comment by earlSt1** [comment]
Hmm. are you seeing entries in the compendium named like `#[CF_tempEntity]`?

Also which system + module version are you using?

**Comment by EvldoaTV** [comment]
no not seeing any faults from the module at all  and running dnd5e and
using latest vrs

**Comment by EvldoaTV** [comment]
2.2.44

**Comment by earlSt1** [comment]
Ah, you need to update to v2.3.1 for FVTT 0.8.x.

**Comment by EvldoaTV** [comment]
Ok un installed and reinstalled the module and it seems to be operating
fine now, thank you so much for your reply however

Sean
