### ISSUE TITLE
Module is not working properly in D&D 3.5 SRD

### ISSUE THREAD

**Issue by irbian** [earlSt1/vtt-compendium-folders#78]
Hi!

Don´t know if the problem comes from the module or 3.5, but is not working properly,

A icon appear on the left of the title of the folder, hiding the title

And some extra buttons on the bottom don´t appear

**Comment by earlSt1** [comment]
Hi, can you send a screenshot of the problem?

Also which version of system + compendium folders are you on?

**Comment by irbian** [comment]
Sure!

Last versions of everything 

Foundry VTT 0.8.6
D35E 0.93.2
Compendium folders 2.3.1

Bugged:
![image](https://user-images.githubusercontent.com/3071767/121092050-e85edf00-c7e2-11eb-8577-be2b25a7b4d2.png)

Not bugged:
![image](https://user-images.githubusercontent.com/3071767/121092165-0f1d1580-c7e3-11eb-9c46-6cb1779a2f71.png)

**Comment by earlSt1** [comment]
Huh, i didnt know about this system! Maybe it has been updated recently which would explain why i havent had any other reports :smile:

I've just pushed an update to the test version which fixes this. Can you uninstall your current compendium folders and install this one using the manifest here: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json

**Comment by irbian** [comment]
Looks ok for me! I´ll ask others using the same system if they found everything allright! :D

**Comment by earlSt1** [comment]
Haha i suspect they will also have the same issues as you. If theyre in desperate need of it working they can also use that manifest i sent you. When i release the next version through foundry it will auto-update.

**Comment by earlSt1** [comment]
Fix included in v2.3.2
