### ISSUE TITLE
Font and icon colors

### ISSUE THREAD

**Issue by GabrielConnor** [earlSt1/vtt-compendium-folders#8]
It would be really helpful if we could change the color of the font and icons of the folders, as white looks weird with some color choices. Awesome module btw, thank you for your work!

**Comment by earlSt1** [comment]
Thanks! I like the feature idea. I'm not sure about the icon colours but font colours are certainly possible. I'll add this to the future section

**Comment by earlSt1** [comment]
So after some testing the default folder icon can be coloured, as well as the text and options buttons. I'll work on adding this to the next release 
![image](https://user-images.githubusercontent.com/13738280/94925322-ece63180-04b6-11eb-8c69-57c3143e7576.png)

**Comment by GabrielConnor** [comment]
Woo! Exciting!

**Comment by earlSt1** [comment]
If you update now, you should get v1.0.6 which has this functionality built in :)
