### ISSUE TITLE
No Compendiums with 'Compendium Folders' and 'German [Pathfinder 2e]' modules

### ISSUE THREAD

**Issue by manfred7168** [earlSt1/vtt-compendium-folders#80]
Hi,
we have a problem with 'compendium folders' and the German translation module 'German [Pathfinder 2e]' (which I'm a team member) on Core 0.8.6
I did not find out what's causing this. There are no messages in the console. Sure we have translated the names of the compendiums too, and we did this with Babele. On Core 0.7.10 we had no such issue.
Could you help us on this?

Manfred

**Comment by earlSt1** [comment]
Hi, so in the sidebar there are just folders and no compendiums in them?

I'm guessing the German translation module is updated for 0.8.6?

**Comment by manfred7168** [comment]
Yes exactly.No Conpendium, just folders.The German Module is compatible to 0.8.6, I'm working with it w/o compandium folders, it works fine.Am 13.06.2021 12:17 schrieb Craig Earl ***@***.***>:
Hi, so in the sidebar there are just folders and no compendiums in them?
I'm guessing the German translation module is updated for 0.8.6?

**Comment by earlSt1** [comment]
Hmm, works for me on latest German Translation version (which for me thats compatible with 0.7.9) and pf2e version, on 0.8.6
![image](https://user-images.githubusercontent.com/13738280/121805741-54f33700-cc44-11eb-9729-bd27528280ba.png)
Which version of pf2e are you running?
Are the compendiums not visible to the GM? (edit a folder and see if there are any at the bottom section)

**Comment by manfred7168** [comment]
I'm working with the newest v2.2.0.6097 of pf2e.
It's weired: When I log on as GM opening a folder (i.e. Actors) showed no compendium. Then I edit this folder "Actors", change nothing and save it ('Ordner aktualisieren"). After that I can open the folder and all compendiums are shown (with translated names).
But when I log out and in again it's like before => no compendiums.

**Comment by earlSt1** [comment]
Do you have the same module versions as me? (apart from Compendium Folders, my test system doesnt show the updated version but its the same as 2.3.1)

**Comment by manfred7168** [comment]
Yes, I do:
![image](https://user-images.githubusercontent.com/84800533/121818573-51819f00-cc88-11eb-97b6-816b6f2fb312.png)

**Comment by earlSt1** [comment]
I'm not sure how babele works. Can you send a screenshot of your module settings? I've got the exact same module versions enabled as you now but am still not getting the issue

**Comment by earlSt1** [comment]
Just discovered the issue from #81, a temporary solution for now is you should be able to click the Refresh button to the left of the search bar in the compendium directory, and it will re-render the directory

**Comment by manfred7168** [comment]
OK, updated today to Core 0.8.7 and module update of Babele to 2.0.5
Problem is gone!

**Comment by earlSt1** [comment]
That is fantastic news. I've been struggling to find out why it was happening 😆
