### ISSUE TITLE
No Compendiums with 'Compendium Folders' and 'French [DnD5e]' modules

### ISSUE THREAD

**Issue by Padhiver** [earlSt1/vtt-compendium-folders#81]
Hello !

Using Compendium Folder with french translation of DnD 5e means that in the end we have no compendium, like in this screenshot : 

![Sans titre](https://user-images.githubusercontent.com/80126915/121890711-f2b93580-cd1a-11eb-8420-9abe937e3785.png)

I dont know if it's the same problem already reported with German Pathfinder so i make a new ticket. All module are up to date, but i dont know if the bug come from Compendium Folder or from the translation. :x

**Comment by earlSt1** [comment]
Hi thanks for the report. Can you send your module + system versions?

Are you also using Babele?

**Comment by Padhiver** [comment]
Thanks to you for the answere.
DnD5e - 1.3.3
Compendium Folder - 2.3.2
Babele - 2.0.3
fr-FR-DND5 System - 1.33.0

And yes, i use Babele.

**Comment by earlSt1** [comment]
Same symptoms as the German issue posted on here earlier. I wonder if Babele has something to do with it.

Thanks for all the info :smile:

**Comment by earlSt1** [comment]
Can you also screenshot your Module settings page? (mainly for Babele and the french translation module)

**Comment by Padhiver** [comment]
Sure, here : 
![Sans titre](https://user-images.githubusercontent.com/80126915/121899249-83e0da00-cd24-11eb-97d9-758683f30e49.png)

Translation if needed : 

Babele : 
Directory of translation files [   FOLDER   ]
enter the directory where the local translation files of the compendium are located

Enable translation export V
enable this option if you wish to add a button on each compendium to generate the translation file, useful as a start-up template

fr-FR - DND5 System :
Disable version control V
allows you to disable the monitoring and possible alerting of an untested version of the Dnd5e system and the Babele module by this translation module

Ignore conversions V
disables conversions and initializations in metric system ... except when the text is hardcoded in the translation ;) and on actor overwriting with the option below

Show the tradFR button V
a small button on the character sheets allowing some additional translations (alignment, classes, etc) when importing campaigns or actors from untranslated compendiums (not directly in the compendium, but in the actors). WARNING: this overwrites the initial values - no going back... (make a copy:))

**Comment by earlSt1** [comment]
Aha, I've managed to replicate it a bit. I changed the Preferred Language in core foundry to French and my folders are all empty on first load (this was the issue with the german ticket). Progress!

If you do get that you should be able to click the Refresh button to the left of the search bar and it will re-render the sidebar

**Comment by Padhiver** [comment]
Oh yep, that work ! 
Refresh button make all compendium coming back in there folder. o.o Thank you !

It's a temporary solution that's pretty easy to use. :'D

**Comment by manfred7168** [comment]
OK, the Reload-Workaround works in the German Version of the issue too. Thank for that.
So, as you now can reproduce the problem, I guess you're still working on a solution?

**Comment by earlSt1** [comment]
Absolutely, it just involves a lot of digging through the
Babele/translation code. Hopefully it ends up being a quick fix :)

**Comment by earlSt1** [comment]
@Padhiver Can you try updating to Babele 2.0.5 and FVTT 0.8.7? @manfred7168 is saying these 2 updates have fixed the issue for him

**Comment by Padhiver** [comment]
Yep worked ! Didnt have the issue anymore. :D Thank you !

**Comment by earlSt1** [comment]
Excellent. As i said to manfred. I've been struggling to find out why it was happening :smile:

I'll close this for now, if you encounter it again we can reopen the issue
