### ISSUE TITLE
Backup Error in 8.7

### ISSUE THREAD

**Issue by mklummis** [earlSt1/vtt-compendium-folders#82]
Compendium Folder itself looks a-okay after migrating from 8.6! (nice)

But, when Exporting to Folder I get multiple copies of my scene folders popping up. All of them except for the final copies are empty. Even after this event, the Compendium itself seems intact and does not have these ghost copies.

**Comment by earlSt1** [comment]
Hi, thanks for raising this, i'll do some testing on it tonight and see if i can replicate it. 

What system version + CF version are you using?

**Comment by mklummis** [comment]
I've fully updated Foundry to 8.7 (and was there during the testing when I saw this issue pop up).
CF is (and was) at 2.3.2, which I believe is fully up to date.

BTW, your mod is insanely useful. Thank you so much. :)

**Comment by earlSt1** [comment]
Thanks :) And sorry when I meant system i meant like D&D, PF2e, etc. 

Also can you send a screenshot of the folders you're trying to export?

**Comment by mklummis** [comment]
I'm on PF2e. :)

I have the shots you need. I'm new to Github, I couldn't see how to add file (don't have permission). How can I get these to ya?

**Comment by earlSt1** [comment]
Ah np, there should be a little chain icon at the top of the text editor (next to Bold, Italics etc). That allows you to attach a file.

Or if you can copy the image file you should be able to paste it directly in the text editor and it will upload it automatically

**Comment by mklummis** [comment]
Attempting to upload (3 shots)

![Dupped Folders](https://user-images.githubusercontent.com/85510877/122265359-a69afc00-cea6-11eb-96a1-b0243555b771.png)

![Scene Folder Structure](https://user-images.githubusercontent.com/85510877/122265383-ab5fb000-cea6-11eb-8c89-80cfd541ee40.png)

![The Compendium Itself](https://user-images.githubusercontent.com/85510877/122265391-ad297380-cea6-11eb-895e-082debcbfb08.png)

**Comment by earlSt1** [comment]
So are you exporting one folder at a time?

Also are you getting any red errors in the F12 console once you export?

**Comment by mklummis** [comment]
I've done both. Some of the folders have nested folders (Westerly Scenes). And They're actually not the triggering factor. Evernight seems to be the one that's the most troubled, and that's just a folder of scenes without any sub folders. Here are shots--I am getting red errors on here, but I also included some white text as well, in case it's pertinent.

![Error 1](https://user-images.githubusercontent.com/85510877/122267381-cf23f580-cea8-11eb-9c69-b802e6690b69.png)
![Error 2](https://user-images.githubusercontent.com/85510877/122267390-d0edb900-cea8-11eb-9d0e-880322076ff2.png)

**Comment by earlSt1** [comment]
Are you exporting the folders with the compendium window open? I think it
should autoclose but i cant remember.

**Comment by mklummis** [comment]
No, I'm just sitting at the scene page without any other windows open. 

I alt click on the folder I'm backing up, select "Export Folder Structure" and get the bug. If I just select "Export to Compendium" I don't get the bug at all. Before 8.7 hit, neither option would cause an error.

**Comment by earlSt1** [comment]
Hmm, could you try disabling all modules other than CF? I wonder if another module is causing that issue.

I'm on 0.8.7 and cant seem to replicate that issue :/

**Comment by mklummis** [comment]
Took off everything except CF and Libwrapper. Problem persists. Sorry that it's such a tricky one. At least it doesn't seem to be corrupting anything (yay!), and I backup constantly. :)

**Comment by Wade0004** [comment]
I'm having a similar issue, using Foundry 0.8.7, DnD5e 1.3.5, and CF 2.3.2

My issue where I have noticed it is that I have created a new folder in my right hand bar that contains a few scenes.  I right click it and export file structure to the compendium with "Merge By Name" checked (one of the scenes is already in the compendium, but not in a folder yet).  It goes through all the motions with no visible errors, but then none of the scenes show up in the compendium. 

![image](https://user-images.githubusercontent.com/74107522/123003659-c16ee400-d370-11eb-8535-44eadd30f6b0.png)

**Comment by Wade0004** [comment]
What is odd is I literally JUST migrated all my scenes from one compendium to another with NO PROBLEM and it kept all the folder structures just by importing them all and then exporting them all to the other compendium.

**Comment by Wade0004** [comment]
I'm totally sorry.  Scrap my comments in their entirety.  I think those scenes are broken.  I'll let you know if I see the issue again as I'm trying to move a lot of stuff from regular compendiums to shared compendiums.  

I think that my issue was the 6 scenes for the battle on the docks were all broken and referenced things that have since been deleted and need to be totally scrapped or rebuilt. It likely has NOTHING to do with this AWESOME module that makes my compendiums soooooo much more bearable.  

thank you for your work.

**Comment by earlSt1** [comment]
> Took off everything except CF and Libwrapper. Problem persists. Sorry that it's such a tricky one. At least it doesn't seem to be corrupting anything (yay!), and I backup constantly. :)

Thats fine, could you try in a brand new world and see if you get the same thing?

**Comment by mklummis** [comment]
I haven't been able to reproduce the error outside of the world where I'm having it. I feel like it's very likely something that happened in the 7.9>7.10>8.7>8.7 chain of migrations. Sorry that I can't give any more info, mate. :)

**Comment by earlSt1** [comment]
Cant find the root cause of this issue. I'll rule it down to the chaos of migrating from 0.7 to 0.8 and close the ticket. If you find anything else ping me on this issue and i'll reopen it.
