### ISSUE TITLE
Compendium Folders fails (for me) after upgrade to 8.7

### ISSUE THREAD

**Issue by Motara7** [earlSt1/vtt-compendium-folders#83]
Foundry VTT 8.7

When I activate the mod, I get the following error and I the mod is not working (no folders, no ability to create folders, etc.).

compendium-folders.js:2931 Uncaught (in promise) TypeError: Cannot read property 'compendiumList' of undefined
    at initFolders (compendium-folders.js:2931)
    at compendium-folders.js:2975
    at Function._call (eval at <anonymous> (libWrapper-error_listeners.js:56), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at Game.setupGame (foundry.js:4307)
    at async Game._initializeGameView (foundry.js:5117)
    at async Game.initialize (foundry.js:4202)

**Comment by earlSt1** [comment]
Hi, I'm guessing for you they worked in 0.8.6?

If so could you send me your Import/Export string? (found in the module settings, you can Copy to Clipboard at the bottom)

**Comment by Motara7** [comment]
Thanks for looking into this for me. I actually went from 7.10 to 8.7. So,
the last version it worked for me was 7.10.
Here is the Import/Export string:

{"cfolder_eurm3njgnwf":{"titleText":"Actor","colorText":"#000000","compendiumList":["SharedData.sm1","SharedData.sm2","SharedData.monsters","SharedData.npcs","SharedData.pcs","SharedData.spelltokenss","world.ironfang-invasion-npcs"],"folderList":[],"_id":"cfolder_eurm3njgnwf"},"cfolder_zwchiuyz03i":{"titleText":"Items
-
Locked","colorText":"#000000","compendiumList":["pf1.armors-and-shields","pf1.class-abilities","pf1.classes","pf1.commonbuffs","pf1.feats","pf1.items","pf1.mythicpaths","pf1.races","pf1.racialhd","pf1.spells","pf1.weapons-and-ammo","pf1.ultimate-equipment","pf1.conditions","pf1.skills","pf-content.pf-goods-services","pf-content.pf-items","pf1e-archetypes.pf-archetypes","pf1e-archetypes.pf-class-abilities","pf1e-archetypes.pf-arch-features","pf1e-archetypes.pf-prestige-classes","pf1e-archetypes.pf-prestige-features","pf-content.pf-feats","pf-content.pf-traits","pf-content.pf-racial-traits","pf-content.pf-magicitems","pf-content.pf-wondrous","pf-content.pf-buffs","pf-content.pf-merchants","pf-content.pf-universal-monster-rules","pf-content.pf-special-qualities"],"folderList":[],"_id":"cfolder_zwchiuyz03i"},"cfolder_4oqizobsktj":{"titleText":"JournalEntry","colorText":"#000000","compendiumList":["pf-content.harrow-deck","pf-content.pf-rules","pf-content.gm-quick-reference"],"folderList":[],"_id":"cfolder_4oqizobsktj"},"cfolder_ejsmzp52axa":{"titleText":"Macro","colorText":"#000000","compendiumList":["pf1.sample-macros","foundry_community_macros.community-macros-misc","foundry_community_macros.community-macros-module-specific","foundry_community_macros.community-macros-roll","foundry_community_macros.community-macros-token","furnace.macros","narrator-tools.narrator-macros","world.my-macros","fxmaster.fxmaster","spellcaster-utility-pf1.spellcaster-macros","tokenmagic.tmMacros","conditional-visibility.Conditional
Visibility","foundry_community_macros.community-macros-pf1e","jb2a_patreon.jb2a-macros","token-attacher.example-macros","trigger-happy.journals","turnAlert.turn-alert-examples","turnAlert.turn-alert-debug"],"folderList":[],"_id":"cfolder_ejsmzp52axa"},"cfolder_5j7tvlx88fp":{"titleText":"RollTable","colorText":"#000000","compendiumList":["pf1.roll-tables","token-mold.adjectives"],"folderList":[],"_id":"cfolder_5j7tvlx88fp"},"cfolder_e0zse4geztk":{"titleText":"Scene","colorText":"#000000","compendiumList":["SharedData.scenes"],"folderList":[],"_id":"cfolder_e0zse4geztk"},"hidden":{"compendiumList":[],"titleText":"hidden-compendiums"},"cfolder_mdp8078k86":{"titleText":"Beastiaries","colorText":"#000000","compendiumList":["pf1.bestiary_1","pf1.bestiary_2","pf1.bestiary_3","pf1.bestiary_4","pf1.bestiary_5","pf1.monster-templates"],"folderList":[],"_id":"cfolder_mdp8078k86"},"cfolder_pykhtiqv2bf":{"titleText":"Items
-
Unlocked","colorText":"#000000","compendiumList":["SharedData.armor","SharedData.buffs","SharedData.lair","SharedData.gear","SharedData.traits","SharedData.classabilities","SharedData.archetypes","SharedData.conditions","SharedData.feats","SharedData.monsterabilities","SharedData.potions","SharedData.racialabilities","SharedData.scrolls","SharedData.spells","SharedData.staves","SharedData.subtypes","SharedData.wands","SharedData.weapons","SharedData.wondrous","SharedData.races","SharedData.classes","SharedData.domains","SharedData.schools","SharedData.bloodlines","SharedData.blessings","SharedData.mysteries"],"folderList":[],"_id":"cfolder_pykhtiqv2bf"},"cfolder_zjrpvxretzl":{"titleText":"Spells
-
Mikko","colorText":"#000000","compendiumList":["world.mikko-1","world.mikko-2","world.mikko-3","world.mikko-4","world.mikko-5","world.mikko-6","world.mikko-7","world.mikko-8","world.mikko-9"],"folderList":[],"_id":"cfolder_zjrpvxretzl"},"cfolder_zh2g3b31tu":{"titleText":"Spells
-
Asher","colorText":"#000000","compendiumList":["world.asher-1","world.asher-2","world.asher-3","world.asher-4","world.asher-5","world.asher-6","world.asher-7","world.asher-8","world.asher-9"],"folderList":[],"_id":"cfolder_zh2g3b31tu"},"cfolder_5lnnlcg1d86":{"titleText":"Spells
-
Gorovash","colorText":"#000000","compendiumList":["world.gorovash-1","world.gorovash-2","world.gorovash-3","world.gorovash-4","world.gorovash-5","world.gorovash-6"],"folderList":[],"_id":"cfolder_5lnnlcg1d86"}}

**Comment by earlSt1** [comment]
How weird, for some reason your default folder is missing. I've seen this happen once before but not sure how it occurs.

If you import this string it will reintroduce the default folder and should allow you to use the module:
```
{"default":{"compendiumList":[],"titleText":"Default","_id":"default","colorText":"#000000"},"cfolder_eurm3njgnwf":{"titleText":"Actor","colorText":"#000000","compendiumList":["SharedData.sm1","SharedData.sm2","SharedData.monsters","SharedData.npcs","SharedData.pcs","SharedData.spelltokenss","world.ironfang-invasion-npcs"],"folderList":[],"_id":"cfolder_eurm3njgnwf"},"cfolder_zwchiuyz03i":{"titleText":"Items - Locked","colorText":"#000000","compendiumList":["pf1.armors-and-shields","pf1.class-abilities","pf1.classes","pf1.commonbuffs","pf1.feats","pf1.items","pf1.mythicpaths","pf1.races","pf1.racialhd","pf1.spells","pf1.weapons-and-ammo","pf1.ultimate-equipment","pf1.conditions","pf1.skills","pf-content.pf-goods-services","pf-content.pf-items","pf1e-archetypes.pf-archetypes","pf1e-archetypes.pf-class-abilities","pf1e-archetypes.pf-arch-features","pf1e-archetypes.pf-prestige-classes","pf1e-archetypes.pf-prestige-features","pf-content.pf-feats","pf-content.pf-traits","pf-content.pf-racial-traits","pf-content.pf-magicitems","pf-content.pf-wondrous","pf-content.pf-buffs","pf-content.pf-merchants","pf-content.pf-universal-monster-rules","pf-content.pf-special-qualities"],"folderList":[],"_id":"cfolder_zwchiuyz03i"},"cfolder_4oqizobsktj":{"titleText":"JournalEntry","colorText":"#000000","compendiumList":["pf-content.harrow-deck","pf-content.pf-rules","pf-content.gm-quick-reference"],"folderList":[],"_id":"cfolder_4oqizobsktj"},"cfolder_ejsmzp52axa":{"titleText":"Macro","colorText":"#000000","compendiumList":["pf1.sample-macros","foundry_community_macros.community-macros-misc","foundry_community_macros.community-macros-module-specific","foundry_community_macros.community-macros-roll","foundry_community_macros.community-macros-token","furnace.macros","narrator-tools.narrator-macros","world.my-macros","fxmaster.fxmaster","spellcaster-utility-pf1.spellcaster-macros","tokenmagic.tmMacros","conditional-visibility.Conditional Visibility","foundry_community_macros.community-macros-pf1e","jb2a_patreon.jb2a-macros","token-attacher.example-macros","trigger-happy.journals","turnAlert.turn-alert-examples","turnAlert.turn-alert-debug"],"folderList":[],"_id":"cfolder_ejsmzp52axa"},"cfolder_5j7tvlx88fp":{"titleText":"RollTable","colorText":"#000000","compendiumList":["pf1.roll-tables","token-mold.adjectives"],"folderList":[],"_id":"cfolder_5j7tvlx88fp"},"cfolder_e0zse4geztk":{"titleText":"Scene","colorText":"#000000","compendiumList":["SharedData.scenes"],"folderList":[],"_id":"cfolder_e0zse4geztk"},"hidden":{"compendiumList":[],"titleText":"hidden-compendiums"},"cfolder_mdp8078k86":{"titleText":"Beastiaries","colorText":"#000000","compendiumList":["pf1.bestiary_1","pf1.bestiary_2","pf1.bestiary_3","pf1.bestiary_4","pf1.bestiary_5","pf1.monster-templates"],"folderList":[],"_id":"cfolder_mdp8078k86"},"cfolder_pykhtiqv2bf":{"titleText":"Items - Unlocked","colorText":"#000000","compendiumList":["SharedData.armor","SharedData.buffs","SharedData.lair","SharedData.gear","SharedData.traits","SharedData.classabilities","SharedData.archetypes","SharedData.conditions","SharedData.feats","SharedData.monsterabilities","SharedData.potions","SharedData.racialabilities","SharedData.scrolls","SharedData.spells","SharedData.staves","SharedData.subtypes","SharedData.wands","SharedData.weapons","SharedData.wondrous","SharedData.races","SharedData.classes","SharedData.domains","SharedData.schools","SharedData.bloodlines","SharedData.blessings","SharedData.mysteries"],"folderList":[],"_id":"cfolder_pykhtiqv2bf"},"cfolder_zjrpvxretzl":{"titleText":"Spells - Mikko","colorText":"#000000","compendiumList":["world.mikko-1","world.mikko-2","world.mikko-3","world.mikko-4","world.mikko-5","world.mikko-6","world.mikko-7","world.mikko-8","world.mikko-9"],"folderList":[],"_id":"cfolder_zjrpvxretzl"},"cfolder_zh2g3b31tu":{"titleText":"Spells - Asher","colorText":"#000000","compendiumList":["world.asher-1","world.asher-2","world.asher-3","world.asher-4","world.asher-5","world.asher-6","world.asher-7","world.asher-8","world.asher-9"],"folderList":[],"_id":"cfolder_zh2g3b31tu"},"cfolder_5lnnlcg1d86":{"titleText":"Spells - Gorovash","colorText":"#000000","compendiumList":["world.gorovash-1","world.gorovash-2","world.gorovash-3","world.gorovash-4","world.gorovash-5","world.gorovash-6"],"folderList":[],"_id":"cfolder_5lnnlcg1d86"}}
```

**Comment by Motara7** [comment]
That did the trick! Thank you so much for your help.

**Comment by earlSt1** [comment]
No problem! I'll close the issue for now :smile:
