### ISSUE TITLE
Error Message when opening an already opened compendium pack

### ISSUE THREAD

**Issue by Sekierer** [earlSt1/vtt-compendium-folders#84]
Heyo,

when attempting to open a compendium while the exact same compendium is open you get the following error. I don't think it matters, but better to report it I guess^^

![image](https://user-images.githubusercontent.com/64690637/122386216-f264a880-cf6d-11eb-8693-1f90e99df78b.png)

Foundry at 0.8.6 and Module at 2.3.2

**Comment by earlSt1** [comment]
Thanks for reporting, was a quick fix (related to the new 0.8.x changes) :smile:

**Comment by earlSt1** [comment]
Fixed in v2.3.3
