### ISSUE TITLE
Drag&Drop sometimes ends in completely different folders

### ISSUE THREAD

**Issue by xenexelen** [earlSt1/vtt-compendium-folders#87]
In some situations, items end up in different subfolders than expected when dragging and dropping.

I have not yet been able to verify the exact cause, but it happens very often after renaming a directory. But it does not only affect the renamed folder, and you can search all folders afterwards first to find out where the item has now been subordinated.

Once the problem occurs, it is impossible to move the item to the desired folder, you can drag it out of the folder structure, but you cannot move it to the desired destination folder (it always ends up in the same "wrong" folder). So far, the only thing that helps me is logging out and logging back in.

It affects all versions I have used of the module so far (whether under Foundry 0.7.9, 0.8.6, 0.8.8...).

I have Foundry hosted by "The Forge", use SWADE as system and "German" as language. My default browser for Foundry is Microsoft Edge.

**Comment by earlSt1** [comment]
Thanks for the report, Is this happening when you have no modules installed?

If so, then I think this may be related to how the folder structure is cached. Instead of logging out and logging in can you try opening another foldered compendium, then closing it and opening the original one?

**Comment by xenexelen** [comment]
I have only the following modules installed (Foundry 0.8.8):
- libWrapper (1.7.3.0)
- Compendium Folders (2.3.2)
- German [Core]
- Savage Worlds Core Ruleset
- As well as a separate, pure content module where I am currently creating a structure with the Compendium Folders module.

Game System is Savage Worlds Adventure Edition (0.19.5)

But I have seen this problem also under Foundry 0.7.x with other systems (and without extensions beyond content modules).

**Comment by xenexelen** [comment]
I have now created a new game, except the Game System only libWrapper and Compendium Folder active and in English language.

1. Create Compendium
2. Drag 4 Items from one System-Compendium to the new one.
3. Create one folder "Test", with 4 Sub-folders "Test1"..."Test4"
4. Drag&Drop 2 Items, one to "Test2", other to "Test4" => okay
5. Rename "Test2" to "Test5", get "Updating Complete" Message.
6. Drag another Item to "Test5" => okay
7. Drag the last Item to "Test3" => This one are moved under "Test5"
8. Back to "the Forge" and "Relaunch" the Game => Now the last Item (7) is under "Test3".

Okay, strange graphics bug and not really intuitive.

**Comment by earlSt1** [comment]
Ok, sounds like this could be related to renaming folders and caching. I'll
do some investigations later this week. Thanks for the step-by-step process
:)

**Comment by earlSt1** [comment]
Sorry for the wait. I found what the issue was (i did not validate the ordering of the folders in the cache after you rename a folder) Can you try using this testing version to see if it fixes it? It does for me. 

To install it just uninstall your current CF version and install it using the manifest link below (bottom of install screen in foundry)
https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json

**Comment by xenexelen** [comment]
The problem seems to be fixed with the change.

**Comment by earlSt1** [comment]
Fixed in v2.3.3
