### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [earlSt1/vtt-compendium-folders#9]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by earlSt1** [comment]
Sounds like a solid idea. I'll start looking into how to add that in and maybe reach out to you for translation advice?

**Comment by lozalojo** [comment]
Yes, but I fear that I wont be able to help you in specific technical questions, since I only translate, I have no idea of js :-)

**Comment by earlSt1** [comment]
I've created a [localization branch](https://github.com/earlSt1/vtt-compendium-folders/tree/localization), and have added some localizations to `lang/en.json` (i've replicated compendium-browser). You can use the module.json in that branch to install, and it will take the latest localization changes.

If you'd like to contribute that would be fantastic, and i'll be more than happy to credit you on the readme :)

**Comment by earlSt1** [comment]
Localization branch merged into master, providing future support for multiple languages
