### ISSUE TITLE
Feature Suggestion: Improve handling of core Foundry Compendium Import when CF is enabled

### ISSUE THREAD

**Issue by Norc** [earlSt1/vtt-compendium-folders#90]
Attempting to import foldered compendiums via the core Foundry import can be problematic.

When CF is enabled, disabling problematic behaviors or providing robust information to the user can help prevent undesired outcomes. Per our discussion in the SWADE channel earlier, here are some thoughts:

> Erceron — Today at 10:01 AM
> + @🌈Norc I was thinking of having it so when you click the Import all button, having a prompt with that warning basically saying what you just put. I dont want to disable it because if you have an unfoldered compendium then it will take away functionality

And a further thought:

> Kristian (Savaged.us Importer) — Today at 10:02 AM
> Couldn’t that context menu or the removal of it be conditional upon it being a foldered compendium?

Thanks!!

**Comment by earlSt1** [comment]
I've gone for Kristian's idea for this one. Later on I could introduce a setting that overrides if people really want the functionality, but at least this way it forces people to use the import method from CF

**Comment by earlSt1** [comment]
Fixed in v2.3.3
