### ISSUE TITLE
Default folder disappears upon renaming

### ISSUE THREAD

**Issue by sethmad** [earlSt1/vtt-compendium-folders#92]
Behavior:

1. In the scenes menu, I selected Export Folder Structure for a folder of scenes.
2. I had no Scene compendiums, so I created a new one called Candlekeep Mysteries
3. I exported a bunch of content to that compendium
4. In the Compendiums menu, I noticed that the new Candlekeep Mysteries compendium was in a top-level folder called Default, so I changed that folder name to Scenes.
5. The folder disappeared from the menu, as did the Candlekeep Mysteries compendium.
6. The Candlekeep Mysteries compendium still exists, because if I export scenes to it using Export Folder Structure, it pops up with all of its content (see screenshot)

I've attached some relevant log lines
![Screen Shot 2021-07-30 at 12 32 09 PM](https://user-images.githubusercontent.com/10540494/127703308-316b3956-7b6d-476b-9984-df61cf91fe57.png)
[compendium folders.log](https://github.com/earlSt1/vtt-compendium-folders/files/6909672/compendium.folders.log)

**Comment by earlSt1** [comment]
Hi, which version of foundry + CF are you using?

**Comment by sethmad** [comment]
Whoops, sorry I left that out:

Foundry 0.8.8
DnD5e 1.4.1
CF 2.3.3

**Comment by earlSt1** [comment]
Ahh ok, so sounds like you changed the default folder name and it disappeared. I'll do some testing tomorrow see if i can replicate it. Thanks for the report! :)

**Comment by MatthewOwens** [comment]
Can confirm that I've hit this issue with:

Foundry 0.8.8
DnD5e 1.4.1
CF 2.3.3

Worth noting that I've also got My Shared Compendia 1.0.0 installed, but I'm not sure if that's causing the issue. When the folder configuration's exported, it looks like the compendiums in the renamed folder have been moved to the 'hidden' folder. Is there any way to get compendiums out of the hidden folder?

**Comment by earlSt1** [comment]
Sorry I forgot to update this ticket. I think I've got it fixed now in my testing version. Can you both test by uninstalling CF and installing using this manifest: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json ?

**Comment by MatthewOwens** [comment]
I've tried uninstalling and using the new manifest, the renamed folder is showing up now - and is populated with compendiums from a newly installed module (still trying to get the initial setup working on my end), however the compendiums that had been moved to the hidden folder are still inaccessable

**Comment by earlSt1** [comment]
Great, to get the hidden compendium to reappear, just edit a folder, scroll to the bottom of the window, and under Unassigned there should be your inaccessible compendium. Tick that box and click Save and it should reveal it again

**Comment by earlSt1** [comment]
Fixed in v2.3.4

**Comment by sethmad** [comment]
I upgraded to 2.3.4, and things seem to be working as expected. Thanks for the fix!
