### ISSUE TITLE
Feature request : Draging folders in compendium

### ISSUE THREAD

**Issue by uniwars** [earlSt1/vtt-compendium-folders#94]
Hi, I would find this very useful to be able to drag folders inside a compendium to make them subfolders or move subfolder from a folder to antoher.

**Comment by earlSt1** [comment]
Hi, I've finally managed to figure out a way to implement this and the feature needs a bit of testing (as well as some others).

If you'd like to test, you can install the test version using this manifest: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/09x-update/test/module.json
I **strongly recommend** backing up all your data first in case something breaks though

**Comment by earlSt1** [comment]
Implemented in v2.4.4
