### ISSUE TITLE
Fix my Compendium issue

### ISSUE THREAD

**Issue by MrPotatoZed** [earlSt1/vtt-compendium-folders#99]
Any assistance would be appreciated. Error message attached.

[8-15-21-monsterfolderdebug.txt](https://github.com/earlSt1/vtt-compendium-folders/files/6988709/8-15-21-monsterfolderdebug.txt)
- FoundryVTT Version 8.8
- Compendium Folders Version 2.5.2
- Game System + Version 5e 1.4.2
- All other modules disabled? (y/n) N

**Comment by earlSt1** [comment]
Hi, would you be able to try the whole process again with the following test version of CF? Here's the manifest link for it, youl need to uninstall your current version and install this version using the manifest: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/082-update/test/module.json

**Comment by earlSt1** [comment]
Fixed in v2.3.51. Note you will likely need to re-import using the muncher for the problems to be gone (I was missing some stuff in the API functions that DDB Importer uses).

**Comment by MrPotatoZed** [comment]
Fix confirmed. Didn't even need to remunch. Thanks again.
